"""Durable storage for the existing single-teacher prototype.

PostgreSQL is the sole production store. Never fall back to local SQLite when
it is unavailable: that would make an unsuccessful durable save look successful.
"""
import json
import sqlite3
from contextlib import closing, contextmanager
from pathlib import Path

import psycopg


class StorageError(Exception):
    """Safe, credential-free message suitable for the UI."""


DOCUMENTS = {
    "teacher_profile": "profile_data",
    "planning_setup": "planning_data",
    "current_learning_position": "position_data",
}
LOCK_ID = 73190421


class Store:
    def __init__(self, database_url):
        if not isinstance(database_url, str) or not database_url.strip():
            raise StorageError(
                "Durable storage is not configured. Add DATABASE_URL to Streamlit Secrets."
            )
        self._database_url = database_url

    @contextmanager
    def _connection(self):
        try:
            # Each operation gets a short-lived connection. Safe after Neon
            # scale-to-zero and Streamlit reruns; no stale global connection.
            with psycopg.connect(
                self._database_url, connect_timeout=15, sslmode="require"
            ) as connection:
                connection.execute("SET LOCAL statement_timeout = '30s'")
                yield connection
        except StorageError:
            raise
        except Exception:
            # Driver errors can contain the connection string. Do not expose it.
            raise StorageError(
                "Teacher AI could not complete the database operation. "
                "Your change has not been confirmed saved. Please try again."
            ) from None

    @staticmethod
    def _lock(connection):
        # Serialise writes for the single-teacher prototype, including migration
        # and date corrections, across sessions/processes. Released on rollback.
        connection.execute("SELECT pg_advisory_xact_lock(%s)", (LOCK_ID,))

    def initialise(self, legacy_path="teacher_ai.db"):
        with self._connection() as connection:
            self._lock(connection)
            for table, column in DOCUMENTS.items():
                connection.execute(
                    f"CREATE TABLE IF NOT EXISTS {table} "
                    f"(id INTEGER PRIMARY KEY, {column} TEXT NOT NULL)"
                )
            connection.execute("""
                CREATE TABLE IF NOT EXISTS actual_progress (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    planning_day TEXT NOT NULL,
                    subject TEXT NOT NULL,
                    lesson_topic TEXT,
                    status TEXT NOT NULL,
                    notes TEXT,
                    planning_date TEXT
                )
            """)
            connection.execute("""
                CREATE INDEX IF NOT EXISTS progress_date_idx
                ON actual_progress (planning_date)
            """)
            connection.execute("""
                CREATE TABLE IF NOT EXISTS storage_migrations (
                    name TEXT PRIMARY KEY
                )
            """)
            marker = connection.execute(
                "SELECT name FROM storage_migrations WHERE name = %s",
                ("legacy_sqlite_v1",),
            ).fetchone()
            if marker is None:
                self._import_legacy(connection, legacy_path)
                connection.execute(
                    "INSERT INTO storage_migrations (name) VALUES (%s)",
                    ("legacy_sqlite_v1",),
                )

    @staticmethod
    def _import_legacy(connection, legacy_path):
        # Import only into a completely empty destination, once, atomically.
        # A stale deployment must never overwrite teacher edits in PostgreSQL.
        for table in [*DOCUMENTS, "actual_progress"]:
            if connection.execute(f"SELECT 1 FROM {table} LIMIT 1").fetchone():
                return
        path = Path(legacy_path)
        if not path.is_file():
            return
        with closing(sqlite3.connect(path.resolve().as_uri() + "?mode=ro", uri=True)) as local:
            tables = {
                row[0] for row in local.execute(
                    "SELECT name FROM sqlite_master WHERE type='table'"
                )
            }
            for table, column in DOCUMENTS.items():
                if table in tables:
                    for row in local.execute(f"SELECT id, {column} FROM {table}"):
                        if not isinstance(json.loads(row[1]), dict):
                            raise ValueError("Invalid legacy document")
                        connection.execute(
                            f"INSERT INTO {table} (id, {column}) VALUES (%s, %s)", row
                        )
            if "actual_progress" in tables:
                columns = {
                    row[1] for row in local.execute("PRAGMA table_info(actual_progress)")
                }
                dated = "planning_date" if "planning_date" in columns else "NULL"
                rows = local.execute(
                    "SELECT planning_day, subject, lesson_topic, status, notes, "
                    f"{dated} FROM actual_progress ORDER BY id"
                )
                for row in rows:
                    connection.execute("""
                        INSERT INTO actual_progress
                        (planning_day, subject, lesson_topic, status, notes, planning_date)
                        VALUES (%s, %s, %s, %s, %s, %s)
                    """, row)

    def load_document(self, name):
        column = DOCUMENTS[name]
        with self._connection() as connection:
            row = connection.execute(
                f"SELECT {column} FROM {name} WHERE id = 1"
            ).fetchone()
            if row is None:
                return {}
            document = json.loads(row[0])
            if not isinstance(document, dict):
                raise StorageError("Saved data could not be read. No data has been replaced.")
            return document

    def save_document(self, name, document):
        column = DOCUMENTS[name]
        encoded = json.dumps(document, ensure_ascii=False)
        with self._connection() as connection:
            self._lock(connection)
            connection.execute(
                f"INSERT INTO {name} (id, {column}) VALUES (1, %s) "
                f"ON CONFLICT (id) DO UPDATE SET {column} = EXCLUDED.{column}",
                (encoded,),
            )

    def load_progress_history(self):
        with self._connection() as connection:
            rows = connection.execute("""
                SELECT id, planning_date, planning_day, status, notes
                FROM actual_progress WHERE planning_date IS NOT NULL
                ORDER BY planning_date ASC, id ASC
            """).fetchall()
        return [
            dict(zip(("id", "planning_date", "planning_day", "status", "notes"),
                     (*row[:4], row[4] or "")))
            for row in rows
        ]

    def load_recent_progress(self, limit=10):
        with self._connection() as connection:
            rows = connection.execute("""
                SELECT planning_day, subject, lesson_topic, status, notes, planning_date
                FROM actual_progress
                ORDER BY COALESCE(planning_date, '') DESC, id DESC LIMIT %s
            """, (limit,)).fetchall()
        keys = ("planning_day", "subject", "lesson_topic", "status", "notes", "planning_date")
        return [dict(zip(keys, row)) for row in rows]

    def save_progress(self, planning_date, planning_day, status, notes):
        with self._connection() as connection:
            self._lock(connection)
            existing = connection.execute("""
                SELECT id FROM actual_progress WHERE planning_date = %s
                ORDER BY id DESC LIMIT 1
            """, (planning_date,)).fetchone()
            values = (planning_day, "Full day", "Daily teaching plan", status, notes)
            if existing:
                connection.execute("""
                    UPDATE actual_progress
                    SET planning_day = %s, subject = %s, lesson_topic = %s,
                        status = %s, notes = %s WHERE id = %s
                """, (*values, existing[0]))
            else:
                connection.execute("""
                    INSERT INTO actual_progress
                    (planning_day, subject, lesson_topic, status, notes, planning_date)
                    VALUES (%s, %s, %s, %s, %s, %s)
                """, (*values, planning_date))
        return existing is not None

    def correct_progress(self, record_id, planning_date, planning_day, status, notes):
        with self._connection() as connection:
            self._lock(connection)
            conflict = connection.execute("""
                SELECT id FROM actual_progress
                WHERE planning_date = %s AND id != %s LIMIT 1
            """, (planning_date, record_id)).fetchone()
            if conflict:
                return False
            result = connection.execute("""
                UPDATE actual_progress
                SET planning_date = %s, planning_day = %s, status = %s, notes = %s
                WHERE id = %s
            """, (planning_date, planning_day, status, notes, record_id))
            if result.rowcount != 1:
                raise StorageError("This progress record no longer exists. Refresh and try again.")
        return True
