"""Durable storage for the existing single-teacher prototype.

PostgreSQL is the sole production store. Never fall back to local SQLite when
it is unavailable: that would make an unsuccessful durable save look successful.
"""
import json
import sqlite3
from contextlib import closing, contextmanager
from datetime import date
from pathlib import Path

from carryover import validate_item, before_date
from monthly_plans import validate_monthly_plan, iso_date
import psycopg
from lesson_progress import (
    LESSON_FIELDS, overall_status, project_learning_position,
    school_date, validate_lessons, validate_plan,
)


class StorageError(Exception):
    """Safe, credential-free message suitable for the UI."""


DOCUMENTS = {
    "teacher_profile": "profile_data",
    "planning_setup": "planning_data",
    "current_learning_position": "position_data",
}
LOCK_ID = 73190421
PERSISTENCE_VERSION = 7


from monthly_learning import LearningStore, validate_item as validate_learning_item, validate_update, MARKER


class Store(LearningStore):
    def __init__(self, database_url):
        if not isinstance(database_url, str) or not database_url.strip():
            raise StorageError(
                "Durable storage is not configured. Add DATABASE_URL to Streamlit Secrets."
            )
        self._database_url = database_url

    @contextmanager
    def _connection(self):
        try:
            # Each operation gets a short-lived connection. Safe after Neon
            # scale-to-zero and Streamlit reruns; no stale global connection.
            with psycopg.connect(
                self._database_url, connect_timeout=15, sslmode="require"
            ) as connection:
                connection.execute("SET LOCAL statement_timeout = '30s'")
                yield connection
        except StorageError:
            raise
        except Exception:
            # Driver errors can contain the connection string. Do not expose it.
            raise StorageError(
                "Teacher AI could not complete the database operation. "
                "Your change has not been confirmed saved. Please try again."
            ) from None

    @staticmethod
    def _lock(connection):
        # Serialise writes for the single-teacher prototype, including migration
        # and date corrections, across sessions/processes. Released on rollback.
        connection.execute("SELECT pg_advisory_xact_lock(%s)", (LOCK_ID,))

    def initialise(self, legacy_path="teacher_ai.db"):
        with self._connection() as connection:
            self._lock(connection)
            for table, column in DOCUMENTS.items():
                connection.execute(
                    f"CREATE TABLE IF NOT EXISTS {table} "
                    f"(id INTEGER PRIMARY KEY, {column} TEXT NOT NULL)"
                )
            connection.execute("""
                CREATE TABLE IF NOT EXISTS actual_progress (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    planning_day TEXT NOT NULL,
                    subject TEXT NOT NULL,
                    lesson_topic TEXT,
                    status TEXT NOT NULL,
                    notes TEXT,
                    planning_date TEXT
                )
            """)
            connection.execute("""
                CREATE INDEX IF NOT EXISTS progress_date_idx
                ON actual_progress (planning_date)
            """)
            connection.execute("""
                CREATE TABLE IF NOT EXISTS storage_migrations (
                    name TEXT PRIMARY KEY
                )
            """)
            # Additive tables leave every historical whole-day record intact.
            connection.execute("""
                CREATE TABLE IF NOT EXISTS day_plans (
                    planning_date TEXT PRIMARY KEY, plan_data TEXT NOT NULL
                )
            """)
            connection.execute("""
                CREATE TABLE IF NOT EXISTS lesson_progress (
                    record_id BIGINT PRIMARY KEY REFERENCES actual_progress(id),
                    lesson_data TEXT NOT NULL
                )
            """)
            connection.execute("""
                CREATE TABLE IF NOT EXISTS monthly_plans (
                    id TEXT PRIMARY KEY, title TEXT NOT NULL,
                    source_filename TEXT NOT NULL, plan_text TEXT NOT NULL,
                    start_date DATE, end_date DATE,
                    CHECK ((start_date IS NULL AND end_date IS NULL) OR
                           (start_date IS NOT NULL AND end_date IS NOT NULL AND start_date <= end_date))
                )
            """)
            connection.execute("CREATE TABLE IF NOT EXISTS period_reviews (period_id TEXT PRIMARY KEY, review_data TEXT NOT NULL)")
            connection.execute("CREATE TABLE IF NOT EXISTS carryover_items (id TEXT PRIMARY KEY, item_data TEXT NOT NULL)")
            connection.execute("CREATE TABLE IF NOT EXISTS monthly_learning_items (id TEXT PRIMARY KEY, item_data TEXT NOT NULL)")
            connection.execute("CREATE TABLE IF NOT EXISTS monthly_item_updates (id TEXT PRIMARY KEY, update_data TEXT NOT NULL)")
            marker = connection.execute(
                "SELECT name FROM storage_migrations WHERE name = %s",
                ("legacy_sqlite_v1",),
            ).fetchone()
            if marker is None:
                self._import_legacy(connection, legacy_path)
                connection.execute(
                    "INSERT INTO storage_migrations (name) VALUES (%s)",
                    ("legacy_sqlite_v1",),
                )

            if connection.execute("SELECT name FROM storage_migrations WHERE name = %s",
                                  ("dated_monthly_v1",)).fetchone() is None:
                self._migrate_monthly(connection)
                connection.execute("INSERT INTO storage_migrations (name) VALUES (%s)", ("dated_monthly_v1",))

    @staticmethod
    def _migrate_monthly(connection):
        row = connection.execute("SELECT planning_data FROM planning_setup WHERE id = 1").fetchone()
        text = json.loads(row[0]).get("monthly_plan_text", "") if row else ""
        if text.strip():
            connection.execute("""INSERT INTO monthly_plans
                (id, title, source_filename, plan_text) VALUES (%s, %s, %s, %s)
                ON CONFLICT (id) DO NOTHING""",
                ("legacy-monthly-plan", "Existing saved plan — confirm dates", "", text))

    @staticmethod
    def _monthly(connection):
        keys = ("id", "title", "source_filename", "plan_text", "start_date", "end_date")
        result = []
        for row in connection.execute("SELECT id, title, source_filename, plan_text, start_date, end_date FROM monthly_plans ORDER BY start_date, title").fetchall():
            item = dict(zip(keys, row))
            for key in ("start_date", "end_date"):
                if item[key] is not None:
                    item[key] = iso_date(item[key])
            result.append(item)
        return result

    def list_monthly_plans(self):
        with self._connection() as connection:
            return self._monthly(connection)

    def select_monthly_plan(self, selected_date):
        selected_date = iso_date(selected_date)
        matches = [p for p in self.list_monthly_plans() if p["start_date"] is not None
                   and p["start_date"] <= selected_date <= p["end_date"]]
        if len(matches) > 1:
            raise StorageError("Overlapping Monthly Plans exist. Correct their dates before generating.")
        return matches[0] if matches else None

    def save_monthly_plan(self, plan, confirmed=False):
        try:
            if confirmed is not True:
                raise ValueError("Dates must be confirmed")
            validate_monthly_plan(plan)
        except (ValueError, TypeError, KeyError):
            raise StorageError("Confirm valid start and end dates and a readable Monthly Plan before saving.") from None
        with self._connection() as connection:
            self._lock(connection)
            for existing in self._monthly(connection):
                if (existing["id"] != plan["id"] and existing["start_date"] is not None
                    and plan["start_date"] <= existing["end_date"] and plan["end_date"] >= existing["start_date"]):
                    raise StorageError("These dates overlap another saved Monthly Plan. Correct the dates before saving.")
            connection.execute("""INSERT INTO monthly_plans
                (id, title, source_filename, plan_text, start_date, end_date)
                VALUES (%s, %s, %s, %s, %s, %s)
                ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title,
                source_filename = EXCLUDED.source_filename, plan_text = EXCLUDED.plan_text,
                start_date = EXCLUDED.start_date, end_date = EXCLUDED.end_date""",
                tuple(plan[key] for key in ("id", "title", "source_filename", "plan_text", "start_date", "end_date")))

    @staticmethod
    def _carryover(connection, as_of=None):
        items = [json.loads(row[0]) for row in connection.execute("SELECT item_data FROM carryover_items ORDER BY id").fetchall()]
        finished = {}
        for row in Store._history(connection):
            if as_of and row["planning_date"] > as_of:
                continue
            for lesson in row.get("lessons", []):
                if lesson["status"] == "Completed":
                    for id in lesson.get("completed_carryover_ids", []):
                        finished[id] = row["planning_date"]
        learning = {i['id']: i for i in Store._learning(connection, as_of)}
        for item in items:
            if item.get('monthly_item_id'):
                linked = learning.get(item['monthly_item_id'])
                if linked:
                    item['learning'] = (linked['remaining'] or linked['description'])[:300]
                    item['subject'] = linked['subject']
                    if linked['archived']:
                        item['state'] = 'removed'
                        item['completion_source'] = 'archived_item'
                    elif item['state'] != 'removed':
                        item['state'] = 'completed' if linked['status'] == 'Completed' else 'outstanding'
                    item['completion_source'] = 'monthly_item'
                continue
            if item["state"] == "outstanding" and item["id"] in finished:
                item["state"] = "completed"
                item["completed_date"] = finished[item["id"]]
                item["completion_source"] = "lesson"
        return [item for item in items if not as_of or item["created_date"] <= as_of]

    def list_carryover(self, as_of=None):
        with self._connection() as connection:
            return self._carryover(connection, as_of)

    def carryover_context(self, monthly, selected_date):
        with self._connection() as connection:
            plans = self._monthly(connection)
            previous = sorted([p for p in plans if p["end_date"] and p["end_date"] < monthly["start_date"]], key=lambda p: p["end_date"])
            row = connection.execute("SELECT review_data FROM period_reviews WHERE period_id = %s", (monthly["id"],)).fetchone()
            prior = previous[-1] if previous else None
            history = [r for r in self._history(connection) if prior and prior["start_date"] <= r["planning_date"] <= prior["end_date"] and r["planning_date"] < selected_date]
            row_position = connection.execute("SELECT position_data FROM current_learning_position WHERE id = 1").fetchone()
            position = before_date(json.loads(row_position[0]) if row_position else {}, prior["end_date"] if prior else selected_date)
            return {"previous": prior, "review": json.loads(row[0]) if row else None,
                    "history": history[-10:], "position": position,
                    "unfinished_items": [i for i in self._learning(connection, selected_date) if prior and i["monthly_plan_id"] == prior["id"] and not i["archived"] and (i["status"] == "In progress" or i["id"] in {link["item_id"] for r in history for lesson in r.get("lessons", []) if lesson["status"] != "Completed" for link in lesson.get("monthly_item_links", [])})][:6],
                    "items": self._carryover(connection, selected_date)}

    def save_period_review(self, monthly, selected_date, items, confirmed=False):
        try:
            school_date(selected_date)
            if not monthly["start_date"] <= selected_date <= monthly["end_date"]:
                raise ValueError("Review date outside confirmed period")
            if confirmed is not True or not isinstance(items, list) or len(items) > 20:
                raise ValueError("Explicit confirmation required")
            for item in items:
                validate_item(item)
                if item["period_id"] != monthly["id"] or item["created_date"] != selected_date or item["state"] != "outstanding":
                    raise ValueError("Invalid review item")
            if len({i["id"] for i in items}) != len(items):
                raise ValueError("Duplicate item")
        except (ValueError, KeyError, TypeError):
            raise StorageError("Confirm valid carryover items before saving. Nothing has been saved.") from None
        with self._connection() as connection:
            self._lock(connection)
            current = next((p for p in self._monthly(connection) if p["id"] == monthly["id"]), None)
            if current != monthly:
                raise StorageError("The Monthly Plan changed. Refresh before confirming carryover.")
            if connection.execute("SELECT period_id FROM period_reviews WHERE period_id = %s", (monthly["id"],)).fetchone():
                raise StorageError("This period was already reviewed in another session. Refresh to see the saved items.")
            known_learning = {i['id']: i for i in self._learning(connection, selected_date)}
            references = [i.get('monthly_item_id') for i in items if i.get('monthly_item_id')]
            if len(references) != len(set(references)) or any(id not in known_learning or known_learning[id]['status'] == 'Completed' or known_learning[id]['archived'] for id in references):
                raise StorageError('Choose distinct unfinished Monthly Plan items for carryover.')
            for item in items:
                connection.execute("INSERT INTO carryover_items (id, item_data) VALUES (%s, %s)", (item["id"], json.dumps(item, ensure_ascii=False)))
            review = {"period_id": monthly["id"], "review_date": selected_date, "nothing_selected": not items, "monthly_plan": {k: monthly[k] for k in ("id", "title", "start_date", "end_date")}}
            connection.execute("INSERT INTO period_reviews (period_id, review_data) VALUES (%s, %s)", (monthly["id"], json.dumps(review)))

    def set_carryover_state(self, id, state):
        if state not in ("completed", "removed", "outstanding"):
            raise StorageError("Invalid carryover action.")
        with self._connection() as connection:
            self._lock(connection)
            row = connection.execute("SELECT item_data FROM carryover_items WHERE id = %s", (id,)).fetchone()
            if not row:
                raise StorageError("This carryover item no longer exists. Refresh.")
            item = json.loads(row[0])
            if item.get('monthly_item_id') and (state == 'completed' or (state == 'outstanding' and item['state'] == 'completed')):
                linked = next(i for i in self._learning(connection) if i['id'] == item['monthly_item_id'])
                from uuid import uuid4
                event = dict(id=uuid4().hex, item_id=linked['id'], status='Completed' if state == 'completed' else 'In progress', remaining='' if state == 'completed' else linked['description'], evidence='Teacher manually changed linked carryover', confirmed_complete=state == 'completed', manual=True, date=date.today().isoformat(), order=max([e['order'] for e in self._learning_events(connection)] + [0]) + 1)
                connection.execute('INSERT INTO monthly_item_updates (id, update_data) VALUES (%s, %s)', (event['id'], json.dumps(event)))
                self._project_position(connection)
            item["state"] = state
            connection.execute("UPDATE carryover_items SET item_data = %s WHERE id = %s", (json.dumps(item, ensure_ascii=False), id))

    @staticmethod
    def _validate_links(plan, lessons):
        for original, outcome in zip(plan["lessons"], lessons):
            if outcome.get("monthly_item_links", []) != original.get("monthly_item_links", []):
                raise StorageError("Monthly learning links changed. Refresh before saving.")
            linked = original.get("carryover_ids", [])
            if outcome.get("carryover_ids", []) != linked or any(id not in linked for id in outcome.get("completed_carryover_ids", [])):
                raise StorageError("Carryover links changed. Refresh before saving progress.")
            if outcome.get("completed_carryover_ids") and outcome["status"] != "Completed":
                raise StorageError("Partial or not-taught lessons cannot finish carryover. Uncheck carryover completion before saving.")

    @staticmethod
    def _import_legacy(connection, legacy_path):
        # Import only into a completely empty destination, once, atomically.
        # A stale deployment must never overwrite teacher edits in PostgreSQL.
        for table in [*DOCUMENTS, "actual_progress", "day_plans", "monthly_plans", "period_reviews", "carryover_items", "monthly_learning_items", "monthly_item_updates"]:
            if connection.execute(f"SELECT 1 FROM {table} LIMIT 1").fetchone():
                return
        path = Path(legacy_path)
        if not path.is_file():
            return
        with closing(sqlite3.connect(path.resolve().as_uri() + "?mode=ro", uri=True)) as local:
            tables = {
                row[0] for row in local.execute(
                    "SELECT name FROM sqlite_master WHERE type='table'"
                )
            }
            for table, column in DOCUMENTS.items():
                if table in tables:
                    for row in local.execute(f"SELECT id, {column} FROM {table}"):
                        if not isinstance(json.loads(row[1]), dict):
                            raise ValueError("Invalid legacy document")
                        connection.execute(
                            f"INSERT INTO {table} (id, {column}) VALUES (%s, %s)", row
                        )
            if "actual_progress" in tables:
                columns = {
                    row[1] for row in local.execute("PRAGMA table_info(actual_progress)")
                }
                dated = "planning_date" if "planning_date" in columns else "NULL"
                rows = local.execute(
                    "SELECT planning_day, subject, lesson_topic, status, notes, "
                    f"{dated} FROM actual_progress ORDER BY id"
                )
                for row in rows:
                    connection.execute("""
                        INSERT INTO actual_progress
                        (planning_day, subject, lesson_topic, status, notes, planning_date)
                        VALUES (%s, %s, %s, %s, %s, %s)
                    """, row)

    def load_document(self, name):
        column = DOCUMENTS[name]
        with self._connection() as connection:
            row = connection.execute(
                f"SELECT {column} FROM {name} WHERE id = 1"
            ).fetchone()
            if row is None:
                return {}
            document = json.loads(row[0])
            if not isinstance(document, dict):
                raise StorageError("Saved data could not be read. No data has been replaced.")
            return document

    def save_document(self, name, document):
        column = DOCUMENTS[name]
        encoded = json.dumps(document, ensure_ascii=False)
        with self._connection() as connection:
            self._lock(connection)
            connection.execute(
                f"INSERT INTO {name} (id, {column}) VALUES (1, %s) "
                f"ON CONFLICT (id) DO UPDATE SET {column} = EXCLUDED.{column}",
                (encoded,),
            )

    def load_progress_history(self):
        with self._connection() as connection:
            return self._history(connection)

    @staticmethod
    def _history(connection, planning_date=None):
        condition = "p.planning_date IS NOT NULL" if planning_date is None else "p.planning_date = %s"
        rows = connection.execute("""
            SELECT p.id, p.planning_date, p.planning_day, p.status, p.notes, l.lesson_data
            FROM actual_progress p LEFT JOIN lesson_progress l ON l.record_id = p.id
            WHERE """ + condition + """
            ORDER BY p.planning_date ASC, p.id ASC
        """, () if planning_date is None else (planning_date,)).fetchall()
        result = []
        for row in rows:
            item = dict(zip(("id", "planning_date", "planning_day", "status", "notes"), row[:5]))
            item["notes"] = item["notes"] or ""
            if row[5]:
                item.update(json.loads(row[5]))
            result.append(item)
        return result

    def load_recent_progress(self, limit=10):
        with self._connection() as connection:
            rows = connection.execute("""
                SELECT p.planning_day, p.subject, p.lesson_topic, p.status, p.notes,
                       p.planning_date, l.lesson_data
                FROM actual_progress p LEFT JOIN lesson_progress l ON l.record_id = p.id
                ORDER BY COALESCE(p.planning_date, '') DESC, p.id DESC LIMIT %s
            """, (limit,)).fetchall()
        keys = ("planning_day", "subject", "lesson_topic", "status", "notes", "planning_date")
        result = []
        for row in rows:
            item = dict(zip(keys, row[:6]))
            if row[6]:
                item.update(json.loads(row[6]))
            result.append(item)
        return result

    def load_day(self, planning_date):
        with self._connection() as connection:
            rows = self._history(connection, planning_date)
            progress = rows[-1] if rows else None
            row = connection.execute(
                "SELECT plan_data FROM day_plans WHERE planning_date = %s", (planning_date,)
            ).fetchone()
            plan = json.loads(row[0]) if row else None
            # Date corrections keep the original lesson snapshot available.
            if progress and progress.get("lessons"):
                plan = {key: progress[key] for key in ("plan_id", "overview", "lessons")}
                plan["planning_date"] = planning_date
                if progress.get("monthly_plan"):
                    plan["monthly_plan"] = progress["monthly_plan"]
        return {"plan": plan, "progress": progress}

    def save_day_plan(self, plan):
        try:
            validate_plan(plan)
        except (ValueError, KeyError, TypeError):
            raise StorageError("The generated lesson list was incomplete. Your saved plan has not been changed.") from None
        with self._connection() as connection:
            self._lock(connection)
            if connection.execute("SELECT id FROM actual_progress WHERE planning_date = %s LIMIT 1",
                                  (plan["planning_date"],)).fetchone():
                raise StorageError("Progress already exists for this date. Review or correct it in Progress History.")
            items = {i['id']: i for i in self._learning(connection, plan['planning_date']) if not i['archived']}
            allowed_periods = {plan.get('monthly_plan', {}).get('id')}
            allowed_ids = {i.get('monthly_item_id') for i in self._carryover(connection, plan['planning_date']) if i['state'] == 'outstanding'}
            for lesson in plan['lessons']:
                for link in lesson.get('monthly_item_links', []):
                    item = items.get(link['item_id'])
                    if not item or item['status'] == 'Completed' or (item['monthly_plan_id'] not in allowed_periods and item['id'] not in allowed_ids):
                        raise StorageError('A linked Monthly Plan item changed. Generate again with the latest items.')
            known = {i["id"] for i in self._carryover(connection, plan["planning_date"]) if i["state"] == "outstanding"}
            if any(id not in known for lesson in plan["lessons"] for id in lesson.get("carryover_ids", [])):
                raise StorageError("A carryover item changed while planning. Generate again with the latest items.")
            connection.execute("""
                INSERT INTO day_plans (planning_date, plan_data) VALUES (%s, %s)
                ON CONFLICT (planning_date) DO UPDATE SET plan_data = EXCLUDED.plan_data
            """, (plan["planning_date"], json.dumps(plan, ensure_ascii=False)))

    @staticmethod
    def _project_position(connection):
        row = connection.execute("SELECT position_data FROM current_learning_position WHERE id = 1").fetchone()
        existing = json.loads(row[0]) if row else {}
        existing = {k: str(v).split(MARKER, 1)[0] for k, v in existing.items()}
        updated = project_learning_position(existing, Store._history(connection))
        from lesson_progress import subject_bucket
        for item in Store._learning(connection):
            if not item['archived'] and item['status'] != 'Not started':
                key = subject_bucket(item['subject'])
                if MARKER not in updated.get(key, ''):
                    updated[key] = updated.get(key, '') + MARKER
                updated[key] += f"- {item.get('last_date', '')} | [{item['id']}] {item['description']}: {item['status']}. Remaining: {item['remaining']}. Teacher evidence: {item['evidence']}\n"
        connection.execute("""
            INSERT INTO current_learning_position (id, position_data) VALUES (1, %s)
            ON CONFLICT (id) DO UPDATE SET position_data = EXCLUDED.position_data
        """, (json.dumps(updated, ensure_ascii=False),))
        return updated

    def save_lesson_progress(self, planning_date, plan_id, lessons):
        try:
            school_date(planning_date)
            validate_lessons(lessons, progress=True)
        except (ValueError, KeyError, TypeError):
            raise StorageError("Choose a status for every lesson and keep notes under 300 characters. Nothing has been saved.") from None
        with self._connection() as connection:
            self._lock(connection)
            rows = self._history(connection, planning_date)
            existing = rows[-1] if rows else None
            if existing and not existing.get("lessons"):
                raise StorageError("This date has a historical whole-day record. Correct it in Progress History.")
            if existing:
                plan = existing
            else:
                row = connection.execute("SELECT plan_data FROM day_plans WHERE planning_date = %s",
                                         (planning_date,)).fetchone()
                plan = json.loads(row[0]) if row else None
            if not plan or plan["plan_id"] != plan_id or [
                {key: item[key] for key in LESSON_FIELDS} for item in plan["lessons"]
            ] != [{key: item[key] for key in LESSON_FIELDS} for item in lessons]:
                raise StorageError("The saved plan changed in another session. Refresh before recording progress.")
            self._validate_links(plan, lessons)
            payload = {"plan_id": plan_id, "overview": plan["overview"], "lessons": lessons}
            if plan.get("monthly_plan"):
                payload["monthly_plan"] = plan["monthly_plan"]
            status = overall_status(lessons)
            notes = "\n".join(f"{item['subject']} — {item['topic']}: {item['status']}"
                              + (f". {item['note']}" if item["note"] else "") for item in lessons)
            day = date.fromisoformat(planning_date).strftime("%A")
            if existing:
                record_id = existing["id"]
                connection.execute("UPDATE actual_progress SET status = %s, notes = %s WHERE id = %s",
                                   (status, notes, record_id))
            else:
                record_id = connection.execute("""
                    INSERT INTO actual_progress (planning_day, subject, lesson_topic, status, notes, planning_date)
                    VALUES (%s, 'Full day', 'Individual planned lessons', %s, %s, %s) RETURNING id
                """, (day, status, notes, planning_date)).fetchone()[0]
            connection.execute("""
                INSERT INTO lesson_progress (record_id, lesson_data) VALUES (%s, %s)
                ON CONFLICT (record_id) DO UPDATE SET lesson_data = EXCLUDED.lesson_data
            """, (record_id, json.dumps(payload, ensure_ascii=False)))
            # Progress and learning evidence commit together; no AI call can
            # leave a paid/failed update between the two durable writes.
            self._save_item_progress(connection, record_id, planning_date, lessons)
            position = self._project_position(connection)
        return position

    def correct_lesson_progress(self, record_id, planning_date, lessons):
        try:
            school_date(planning_date)
            validate_lessons(lessons, progress=True)
        except (ValueError, KeyError, TypeError):
            raise StorageError("Invalid lesson correction. Nothing has been saved.") from None
        with self._connection() as connection:
            self._lock(connection)
            existing = next((row for row in self._history(connection) if row["id"] == record_id), None)
            if not existing or not existing.get("lessons"):
                raise StorageError("This lesson record no longer exists. Refresh and try again.")
            if [{key: item[key] for key in LESSON_FIELDS} for item in existing["lessons"]] != [
                {key: item[key] for key in LESSON_FIELDS} for item in lessons
            ]:
                raise StorageError("The lesson snapshot changed. Refresh before correcting it.")
            if connection.execute("SELECT id FROM actual_progress WHERE planning_date = %s AND id != %s LIMIT 1",
                                  (planning_date, record_id)).fetchone():
                return None
            self._validate_links(existing, lessons)
            payload = {key: existing[key] for key in ("plan_id", "overview")}
            payload["lessons"] = lessons
            if existing.get("monthly_plan"):
                payload["monthly_plan"] = existing["monthly_plan"]
            notes = "\n".join(f"{item['subject']} — {item['topic']}: {item['status']}"
                              + (f". {item['note']}" if item["note"] else "") for item in lessons)
            connection.execute("""
                UPDATE actual_progress SET planning_date = %s, planning_day = %s,
                status = %s, notes = %s WHERE id = %s
            """, (planning_date, date.fromisoformat(planning_date).strftime("%A"),
                  overall_status(lessons), notes, record_id))
            connection.execute("UPDATE lesson_progress SET lesson_data = %s WHERE record_id = %s",
                               (json.dumps(payload, ensure_ascii=False), record_id))
            self._save_item_progress(connection, record_id, planning_date, lessons)
            return self._project_position(connection)

    def save_progress(self, planning_date, planning_day, status, notes):
        with self._connection() as connection:
            self._lock(connection)
            existing = connection.execute("""
                SELECT id FROM actual_progress WHERE planning_date = %s
                ORDER BY id DESC LIMIT 1
            """, (planning_date,)).fetchone()
            if existing and connection.execute("SELECT record_id FROM lesson_progress WHERE record_id = %s",
                                               (existing[0],)).fetchone():
                raise StorageError("This date has individual lesson progress. Use the lesson correction controls.")
            values = (planning_day, "Full day", "Daily teaching plan", status, notes)
            if existing:
                connection.execute("""
                    UPDATE actual_progress
                    SET planning_day = %s, subject = %s, lesson_topic = %s,
                        status = %s, notes = %s WHERE id = %s
                """, (*values, existing[0]))
            else:
                connection.execute("""
                    INSERT INTO actual_progress
                    (planning_day, subject, lesson_topic, status, notes, planning_date)
                    VALUES (%s, %s, %s, %s, %s, %s)
                """, (*values, planning_date))
        return existing is not None

    def correct_progress(self, record_id, planning_date, planning_day, status, notes):
        with self._connection() as connection:
            self._lock(connection)
            if connection.execute("SELECT record_id FROM lesson_progress WHERE record_id = %s", (record_id,)).fetchone():
                raise StorageError("Use the individual lesson controls to correct this record.")
            conflict = connection.execute("""
                SELECT id FROM actual_progress
                WHERE planning_date = %s AND id != %s LIMIT 1
            """, (planning_date, record_id)).fetchone()
            if conflict:
                return False
            result = connection.execute("""
                UPDATE actual_progress
                SET planning_date = %s, planning_day = %s, status = %s, notes = %s
                WHERE id = %s
            """, (planning_date, planning_day, status, notes, record_id))
            if result.rowcount != 1:
                raise StorageError("This progress record no longer exists. Refresh and try again.")
        return True

    def export_backup(self):
        with self._connection() as connection:
            self._lock(connection)
            backup = {"format_version": 5}
            for table, column in DOCUMENTS.items():
                row = connection.execute(
                    f"SELECT {column} FROM {table} WHERE id = 1"
                ).fetchone()
                backup[table] = json.loads(row[0]) if row else {}
            keys = ("id", "planning_day", "subject", "lesson_topic", "status", "notes", "planning_date")
            rows = connection.execute(
                "SELECT id, planning_day, subject, lesson_topic, status, notes, "
                "planning_date FROM actual_progress ORDER BY id"
            ).fetchall()
            backup["actual_progress"] = [dict(zip(keys, row)) for row in rows]
            lesson_rows = {row[0]: json.loads(row[1]) for row in connection.execute(
                "SELECT record_id, lesson_data FROM lesson_progress"
            ).fetchall()}
            for row in backup["actual_progress"]:
                if row["id"] in lesson_rows:
                    row.update(lesson_rows[row["id"]])
            backup["monthly_learning_items"] = self._learning_raw(connection)
            backup["monthly_item_updates"] = self._learning_events(connection)
            backup["period_reviews"] = [json.loads(row[0]) for row in connection.execute("SELECT review_data FROM period_reviews ORDER BY period_id").fetchall()]
            backup["carryover_items"] = [json.loads(row[0]) for row in connection.execute("SELECT item_data FROM carryover_items ORDER BY id").fetchall()]
            backup["monthly_plans"] = self._monthly(connection)
            backup["day_plans"] = [json.loads(row[0]) for row in connection.execute(
                "SELECT plan_data FROM day_plans ORDER BY planning_date"
            ).fetchall()]
        return backup

    def restore_backup(self, backup):
        # Validate the whole upload before starting any write.
        try:
            if not isinstance(backup, dict) or backup.get("format_version") not in (1, 2, 3, 4, 5):
                raise ValueError("Unsupported backup")
            if not all(isinstance(backup.get(table), dict) for table in DOCUMENTS):
                raise ValueError("Missing documents")
            rows = backup["actual_progress"]
            if not isinstance(rows, list):
                raise ValueError("Invalid progress")
            for row in rows:
                if not isinstance(row, dict):
                    raise ValueError("Invalid record")
                for key in ("planning_day", "subject", "status"):
                    if not isinstance(row.get(key), str):
                        raise ValueError("Missing record field")
                if row["status"] not in ("Completed", "Partially completed", "Not taught"):
                    raise ValueError("Invalid progress status")
                for key in ("lesson_topic", "notes", "planning_date"):
                    if row.get(key) is not None and not isinstance(row[key], str):
                        raise ValueError("Invalid optional field")
                if row.get("planning_date") is not None:
                    if date.fromisoformat(row["planning_date"]).isoformat() != row["planning_date"]:
                        raise ValueError("Invalid school date")
                if "lessons" in row:
                    validate_plan({**row, "planning_date": row["planning_date"]})
                    validate_lessons(row["lessons"], progress=True)
                    if overall_status(row["lessons"]) != row["status"]:
                        raise ValueError("Inconsistent day summary")
            plans = backup.get("day_plans", [])
            if not isinstance(plans, list):
                raise ValueError("Invalid plans")
            monthly = backup["monthly_plans"] if backup["format_version"] >= 3 else []
            if not isinstance(monthly, list):
                raise ValueError("Invalid monthly plans")
            ids = set()
            for item in monthly:
                validate_monthly_plan(item, allow_pending=True)
                if item["id"] in ids:
                    raise ValueError("Duplicate monthly plan")
                ids.add(item["id"])
            confirmed = sorted([p for p in monthly if p["start_date"]], key=lambda p: p["start_date"])
            if any(a["end_date"] >= b["start_date"] for a, b in zip(confirmed, confirmed[1:])):
                raise ValueError("Overlapping monthly plans")
            reviews = backup.get("period_reviews", []) if backup["format_version"] >= 4 else []
            carry_items = backup.get("carryover_items", []) if backup["format_version"] >= 4 else []
            if not isinstance(reviews, list) or not isinstance(carry_items, list):
                raise ValueError("Invalid carryover backup")
            if len({r["period_id"] for r in reviews}) != len(reviews) or len({i["id"] for i in carry_items}) != len(carry_items):
                raise ValueError("Duplicate carryover backup")
            for review in reviews:
                school_date(review["review_date"])
                if review["period_id"] not in ids or not isinstance(review["nothing_selected"], bool):
                    raise ValueError("Invalid period review")
            for item in carry_items:
                validate_item(item)
                if item["period_id"] not in {r["period_id"] for r in reviews}:
                    raise ValueError("Missing period review")
            learning = backup.get('monthly_learning_items', []) if backup['format_version'] >= 5 else []
            updates = backup.get('monthly_item_updates', []) if backup['format_version'] >= 5 else []
            if not isinstance(learning, list) or not isinstance(updates, list):
                raise ValueError('Invalid learning backup')
            learning_ids = set()
            for item in learning:
                validate_learning_item(item)
                if item['id'] in learning_ids or item['monthly_plan_id'] not in ids:
                    raise ValueError('Invalid learning reference')
                learning_ids.add(item['id'])
            if len({u['id'] for u in updates}) != len(updates):
                raise ValueError('Duplicate updates')
            for update in updates:
                validate_update(update)
                school_date(update['date'])
                if update['item_id'] not in learning_ids or not isinstance(update['order'], int) or (update.get('record_id') is not None and update['record_id'] not in {r.get('id') for r in rows if r.get('lessons')}):
                    raise ValueError('Invalid update reference')
            for item in carry_items:
                if item.get('monthly_item_id') and item['monthly_item_id'] not in learning_ids:
                    raise ValueError('Unknown carryover learning')
            for saved in plans + rows:
                for lesson in saved.get('lessons', []):
                    if any(link['item_id'] not in learning_ids for link in lesson.get('monthly_item_links', [])):
                        raise ValueError('Unknown lesson learning')
            dates = set()
            for plan in plans:
                validate_plan(plan)
                if plan["planning_date"] in dates:
                    raise ValueError("Duplicate saved plan")
                dates.add(plan["planning_date"])
        except (ValueError, KeyError, TypeError):
            raise StorageError("This is not a valid Teacher AI backup. No saved data has been changed.") from None
        with self._connection() as connection:
            self._lock(connection)
            # Never overwrite existing durable teacher edits through restore.
            for table in [*DOCUMENTS, "actual_progress", "day_plans", "lesson_progress", "monthly_plans", "period_reviews", "carryover_items", "monthly_learning_items", "monthly_item_updates"]:
                if connection.execute(f"SELECT 1 FROM {table} LIMIT 1").fetchone():
                    return False
            for table, column in DOCUMENTS.items():
                connection.execute(
                    f"INSERT INTO {table} (id, {column}) VALUES (1, %s)",
                    (json.dumps(backup[table], ensure_ascii=False),),
                )
            record_ids = {}
            for row in rows:
                record_id = connection.execute("""
                    INSERT INTO actual_progress
                    (planning_day, subject, lesson_topic, status, notes, planning_date)
                    VALUES (%s, %s, %s, %s, %s, %s) RETURNING id
                """, tuple(row.get(key) for key in (
                    "planning_day", "subject", "lesson_topic", "status", "notes", "planning_date"
                ))).fetchone()[0]
                if "id" in row:
                    record_ids[row["id"]] = record_id
                if "lessons" in row:
                    payload = {key: row[key] for key in ("plan_id", "overview", "lessons")}
                    if row.get("monthly_plan"):
                        payload["monthly_plan"] = row["monthly_plan"]
                    connection.execute("INSERT INTO lesson_progress (record_id, lesson_data) VALUES (%s, %s)",
                                       (record_id, json.dumps(payload, ensure_ascii=False)))
            for plan in plans:
                connection.execute("INSERT INTO day_plans (planning_date, plan_data) VALUES (%s, %s)",
                                   (plan["planning_date"], json.dumps(plan, ensure_ascii=False)))
            for item in monthly:
                connection.execute("INSERT INTO monthly_plans (id, title, source_filename, plan_text, start_date, end_date) VALUES (%s, %s, %s, %s, %s, %s)",
                                   tuple(item[key] for key in ("id", "title", "source_filename", "plan_text", "start_date", "end_date")))
            if backup["format_version"] < 3:
                self._migrate_monthly(connection)
            for review in reviews:
                connection.execute("INSERT INTO period_reviews (period_id, review_data) VALUES (%s, %s)", (review["period_id"], json.dumps(review)))
            for item in carry_items:
                connection.execute("INSERT INTO carryover_items (id, item_data) VALUES (%s, %s)", (item["id"], json.dumps(item, ensure_ascii=False)))
            for item in learning:
                connection.execute('INSERT INTO monthly_learning_items (id, item_data) VALUES (%s, %s)', (item['id'], json.dumps(item)))
            for update in updates:
                update = dict(update)
                if 'record_id' in update:
                    update['record_id'] = record_ids[update['record_id']]
                connection.execute('INSERT INTO monthly_item_updates (id, update_data) VALUES (%s, %s)', (update['id'], json.dumps(update)))
        return True
