"""Run locally with a SQLite SQL adapter; CI also runs against real PostgreSQL."""
import json
import os
import sqlite3
import tempfile
import unittest
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from unittest.mock import patch
from urllib.parse import urlparse

import psycopg
from persistence import DOCUMENTS, Store, StorageError
from fixtures import sample_plan, outcomes
from lesson_progress import EVIDENCE_MARKER


class SQLiteAdapter:
    """Test-only adapter; production never uses this fallback."""
    def __init__(self, path):
        self.connection = sqlite3.connect(path, timeout=30)

    def __enter__(self):
        return self

    def __exit__(self, kind, value, traceback):
        try:
            if kind is None:
                self.connection.commit()
            else:
                self.connection.rollback()
        finally:
            self.connection.close()

    def execute(self, sql, params=()):
        if sql.startswith("SET LOCAL"):
            return self.connection.execute("SELECT 1")
        if "pg_advisory_xact_lock" in sql:
            self.connection.execute("BEGIN IMMEDIATE")
            return self.connection.execute("SELECT 1")
        sql = sql.replace(
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "INTEGER PRIMARY KEY AUTOINCREMENT",
        ).replace("%s", "?")
        return self.connection.execute(sql, params)


class StoreTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.legacy = self.root / "legacy.db"
        self.url = os.environ.get("TEST_DATABASE_URL", "test-only")
        if self.url != "test-only":
            parsed = urlparse(self.url)
            if parsed.hostname not in ("localhost", "127.0.0.1") or parsed.path != "/test_teacher_ai":
                raise RuntimeError("Integration tests only accept a local test_teacher_ai database")
            self.real_connect = psycopg.connect
            with self.real_connect(self.url) as connection:
                for table in ["lesson_progress", "day_plans", *DOCUMENTS, "actual_progress", "storage_migrations"]:
                    connection.execute(f"DROP TABLE IF EXISTS {table}")
            def connect(url, **kwargs):
                # The isolated CI localhost service has no TLS; production
                # continues to require it.
                kwargs["sslmode"] = "disable"
                return self.real_connect(url, **kwargs)
        else:
            def connect(url, **kwargs):
                return SQLiteAdapter(self.root / "remote.db")
        self.connect = connect
        self.patcher = patch("persistence.psycopg.connect", side_effect=connect)
        self.patcher.start()
        self.store = Store(self.url)
        self.store.initialise(self.legacy)

    def tearDown(self):
        self.patcher.stop()
        self.temp.cleanup()

    def create_legacy(self, invalid=False, dated=True):
        with sqlite3.connect(self.legacy) as connection:
            for table, column in DOCUMENTS.items():
                connection.execute(f"CREATE TABLE {table} (id INTEGER PRIMARY KEY, {column} TEXT)")
                value = "bad-json" if invalid and table == "planning_setup" else json.dumps({"value": table})
                connection.execute(f"INSERT INTO {table} VALUES (1, ?)", (value,))
            connection.execute("""
                CREATE TABLE actual_progress (
                    id INTEGER PRIMARY KEY, planning_day TEXT, subject TEXT,
                    lesson_topic TEXT, status TEXT, notes TEXT
                )
            """)
            if dated:
                connection.execute("ALTER TABLE actual_progress ADD COLUMN planning_date TEXT")
                connection.execute(
                    "INSERT INTO actual_progress VALUES (9, 'Wednesday', 'Full day', 'Daily teaching plan', "
                    "'Partially completed', 'Gaeilge missed', '2026-09-30')"
                )
            else:
                connection.execute(
                    "INSERT INTO actual_progress VALUES (9, 'Wednesday', 'Full day', 'Daily teaching plan', "
                    "'Partially completed', 'Gaeilge missed')"
                )

    def reset_migration(self):
        with self.connect(self.url) as connection:
            connection.execute("DELETE FROM storage_migrations")

    def test_all_four_areas_survive_fresh_store_and_runtime_loss(self):
        for name in DOCUMENTS:
            self.store.save_document(name, {"text": "Am Don Léamh", "count": 27})
        self.store.save_progress("2026-09-30", "Wednesday", "Partially completed", "English unfinished")
        # A redeployment has no old local file, only the same external database.
        fresh = Store(self.url)
        fresh.initialise(self.root / "new-runtime" / "missing.db")
        for name in DOCUMENTS:
            self.assertEqual(fresh.load_document(name), {"text": "Am Don Léamh", "count": 27})
        self.assertEqual(fresh.load_progress_history()[0]["notes"], "English unfinished")
        self.assertEqual(fresh.load_recent_progress()[0]["planning_date"], "2026-09-30")

    def test_progress_updates_one_date_and_corrections_reject_conflicts(self):
        self.assertFalse(self.store.save_progress("2026-09-30", "Wednesday", "Completed", "Maths done"))
        self.assertTrue(self.store.save_progress("2026-09-30", "Wednesday", "Not taught", "Assembly"))
        self.store.save_progress("2026-10-01", "Thursday", "Completed", "English done")
        history = self.store.load_progress_history()
        self.assertEqual(len(history), 2)
        self.assertFalse(self.store.correct_progress(history[0]["id"], "2026-10-01", "Thursday", "Completed", "conflict"))
        self.assertEqual(self.store.load_progress_history(), history)
        self.assertTrue(self.store.correct_progress(history[0]["id"], "2026-09-29", "Tuesday", "Partially completed", "corrected"))
        self.assertEqual(self.store.load_progress_history()[0]["notes"], "corrected")

    def test_concurrent_saves_do_not_duplicate_progress(self):
        def save(index):
            return self.store.save_progress("2026-09-30", "Wednesday", "Completed", str(index))
        with ThreadPoolExecutor(max_workers=4) as pool:
            list(pool.map(save, range(8)))
        self.assertEqual(len(self.store.load_progress_history()), 1)

    def test_migration_is_complete_once_and_does_not_overwrite_edits(self):
        self.create_legacy()
        self.reset_migration()
        self.store.initialise(self.legacy)
        for name in DOCUMENTS:
            self.assertEqual(self.store.load_document(name), {"value": name})
        self.assertEqual(len(self.store.load_progress_history()), 1)
        self.store.save_document("teacher_profile", {"value": "newer teacher edit"})
        self.store.initialise(self.legacy)
        self.assertEqual(self.store.load_document("teacher_profile"), {"value": "newer teacher edit"})
        self.assertEqual(len(self.store.load_progress_history()), 1)
        self.store.save_progress("2026-10-01", "Thursday", "Completed", "new record")
        self.assertEqual(len(self.store.load_progress_history()), 2)

    def test_legacy_undated_progress_is_preserved(self):
        self.create_legacy(dated=False)
        self.reset_migration()
        self.store.initialise(self.legacy)
        self.assertEqual(self.store.load_progress_history(), [])
        self.assertEqual(self.store.load_recent_progress()[0]["notes"], "Gaeilge missed")
        self.assertIsNone(self.store.load_recent_progress()[0]["planning_date"])

    def test_migration_rolls_back_all_data_on_invalid_legacy_json(self):
        self.create_legacy(invalid=True)
        self.reset_migration()
        with self.assertRaises(StorageError):
            self.store.initialise(self.legacy)
        self.assertEqual(self.store.load_document("teacher_profile"), {})
        with self.connect(self.url) as connection:
            self.assertIsNone(connection.execute("SELECT name FROM storage_migrations").fetchone())

    def test_nonempty_destination_is_never_overwritten_by_legacy(self):
        self.store.save_document("current_learning_position", {"Maths": "Subtraction"})
        self.create_legacy()
        self.reset_migration()
        self.store.initialise(self.legacy)
        self.assertEqual(self.store.load_document("current_learning_position"), {"Maths": "Subtraction"})
        self.assertEqual(self.store.load_document("teacher_profile"), {})

    def test_failure_is_safe_and_never_falls_back(self):
        with patch("persistence.psycopg.connect", side_effect=RuntimeError("password=VERY_PRIVATE")):
            with self.assertRaises(StorageError) as error:
                self.store.save_document("teacher_profile", {"new": "value"})
        self.assertNotIn("VERY_PRIVATE", str(error.exception))
        self.assertEqual(self.store.load_document("teacher_profile"), {})
        with self.assertRaises(StorageError):
            Store("")

    def test_backup_roundtrip_and_nonempty_restore_refused(self):
        backup = {
            "format_version": 1,
            "teacher_profile": {"class_level": "5th Class"},
            "planning_setup": {"monthly_plan_text": "Irish: Mé Féin"},
            "current_learning_position": {"Maths": "Subtraction"},
            "actual_progress": [{
                "planning_day": "Wednesday", "subject": "Full day",
                "lesson_topic": "Daily teaching plan", "status": "Partially completed",
                "notes": "Gaeilge missed", "planning_date": "2026-09-30",
            }],
        }
        self.assertTrue(self.store.restore_backup(backup))
        exported = self.store.export_backup()
        for name in DOCUMENTS:
            self.assertEqual(exported[name], backup[name])
        self.assertEqual(exported["actual_progress"][0]["notes"], "Gaeilge missed")
        self.assertFalse(self.store.restore_backup(backup))
        self.assertEqual(self.store.export_backup(), exported)

    def test_invalid_backup_does_not_write_partial_data(self):
        with self.assertRaises(StorageError):
            self.store.restore_backup({
                "format_version": 1,
                "teacher_profile": {"value": "must not be saved"},
                "planning_setup": {}, "current_learning_position": {},
                "actual_progress": [{"planning_day": "Wednesday", "subject": "Full day",
                    "status": "Completed", "planning_date": "not-a-date"}],
            })
        self.assertEqual(self.store.load_document("teacher_profile"), {})

    def save_sample(self, day="2026-09-30"):
        plan = sample_plan(day)
        self.store.save_day_plan(plan)
        position = self.store.save_lesson_progress(day, plan["plan_id"], outcomes(plan))
        return plan, position

    def test_lesson_snapshot_and_learning_survive_runtime_loss_and_retry(self):
        self.store.save_document("current_learning_position", {"Maths": "Addition completed", "Other": "Friday Art"})
        plan, position = self.save_sample()
        fresh = Store(self.url)
        fresh.initialise(self.root / "missing-again.db")
        self.assertEqual(fresh.load_day(plan["planning_date"])["progress"]["lessons"], outcomes(plan))
        self.assertEqual(fresh.load_recent_progress()[0]["lessons"], outcomes(plan))
        self.assertEqual(fresh.load_document("current_learning_position"), position)
        self.assertIn("Addition completed", position["Maths"])
        self.assertEqual(position["Other"], "Friday Art")
        self.assertEqual(fresh.save_lesson_progress(plan["planning_date"], plan["plan_id"], outcomes(plan)), position)
        self.assertEqual(len(fresh.load_progress_history()), 1)

    def test_plan_regeneration_rejects_stale_lesson_ids_and_preserves_saved_progress(self):
        first = sample_plan()
        self.store.save_day_plan(first)
        replacement = sample_plan()
        self.store.save_day_plan(replacement)
        with self.assertRaises(StorageError):
            self.store.save_lesson_progress(first["planning_date"], first["plan_id"], outcomes(first))
        self.assertEqual(self.store.load_progress_history(), [])
        self.store.save_lesson_progress(replacement["planning_date"], replacement["plan_id"], outcomes(replacement))
        with self.assertRaises(StorageError):
            self.store.save_day_plan(sample_plan())
        with self.assertRaises(StorageError):
            self.store.save_progress("2026-09-30", "Wednesday", "Completed", "Cannot replace lessons")
        tampered = outcomes(replacement)
        tampered[0]["learning_intention"] = "Finish the whole unit"
        with self.assertRaises(StorageError):
            self.store.save_lesson_progress(replacement["planning_date"], replacement["plan_id"], tampered)
        self.assertEqual(self.store.load_progress_history()[0]["lessons"], outcomes(replacement))

    def test_lessons_and_learning_rollback_together_if_update_fails(self):
        plan = sample_plan()
        self.store.save_day_plan(plan)
        self.store.save_document("current_learning_position", {"English": "Known starting position"})
        with patch.object(Store, "_project_position", side_effect=RuntimeError("private connection string")):
            with self.assertRaises(StorageError) as error:
                self.store.save_lesson_progress(plan["planning_date"], plan["plan_id"], outcomes(plan))
        self.assertNotIn("private", str(error.exception))
        self.assertEqual(self.store.load_progress_history(), [])
        self.assertEqual(self.store.load_document("current_learning_position"), {"English": "Known starting position"})

    def test_concurrent_lesson_saves_keep_one_day_and_matching_learning(self):
        plan = sample_plan()
        self.store.save_day_plan(plan)
        def save(index):
            recorded = outcomes(plan)
            recorded[1]["note"] = f"Unfinished detail {index}"
            return self.store.save_lesson_progress(plan["planning_date"], plan["plan_id"], recorded)
        with ThreadPoolExecutor(max_workers=4) as pool:
            list(pool.map(save, range(8)))
        history = self.store.load_progress_history()
        self.assertEqual(len(history), 1)
        self.assertIn(history[0]["lessons"][1]["note"], self.store.load_document("current_learning_position")["English"])

    def test_correction_moves_date_and_removes_obsolete_outcomes(self):
        plan, old_position = self.save_sample()
        row = self.store.load_progress_history()[0]
        changed = outcomes(plan)
        changed[1].update(status="Completed", note="Finished the final activity")
        updated = self.store.correct_lesson_progress(row["id"], "2026-09-29", changed)
        self.assertNotIn("didn't finish", updated["English"])
        self.assertNotIn("2026-09-30", updated["English"])
        self.assertIn("2026-09-29", updated["English"])
        self.assertIn("Finished the final activity", updated["English"])
        self.assertEqual(self.store.load_day("2026-09-29")["plan"]["lessons"], changed)
        self.store.save_progress("2026-10-01", "Thursday", "Completed", "Legacy")
        before = self.store.export_backup()
        self.assertIsNone(self.store.correct_lesson_progress(row["id"], "2026-10-01", changed))
        self.assertEqual(self.store.export_backup(), before)

    def test_repeated_subjects_are_distinct_and_notes_override_planned_learning(self):
        import copy
        plan = sample_plan()
        second = copy.deepcopy(plan["lessons"][1])
        second.update(lesson_id="second-english", topic="Reading comprehension", time="13:50–14:20",
                      learning_intention="Explain the character's motive.")
        plan["lessons"].append(second)
        self.store.save_day_plan(plan)
        recorded = outcomes(plan)
        recorded[-1].update(status="Completed", note="Changed lesson: practised spelling instead; no reading taught")
        position = self.store.save_lesson_progress(plan["planning_date"], plan["plan_id"], recorded)
        self.assertIn("Narrative openings", position["English"])
        self.assertIn("Reading comprehension", position["English"])
        self.assertIn("authoritative): Changed lesson", position["English"])
        self.assertIn("no reading taught", position["English"])
        self.assertEqual(len(self.store.load_progress_history()[0]["lessons"]), 4)

    def test_new_backup_roundtrip_preserves_plans_and_lesson_snapshots(self):
        plan, position = self.save_sample()
        backup = self.store.export_backup()
        self.assertEqual(backup["format_version"], 2)
        with self.connect(self.url) as connection:
            for table in ["lesson_progress", "day_plans", "actual_progress", *DOCUMENTS]:
                connection.execute(f"DELETE FROM {table}")
        self.assertTrue(self.store.restore_backup(backup))
        restored = self.store.load_progress_history()[0]
        self.assertEqual(restored["lessons"], outcomes(plan))
        self.assertEqual(restored["plan_id"], plan["plan_id"])
        self.assertEqual(self.store.load_day(plan["planning_date"])["plan"]["plan_id"], plan["plan_id"])
        self.assertEqual(self.store.load_document("current_learning_position"), position)
        self.assertFalse(self.store.restore_backup(backup))

    def test_invalid_lesson_or_backup_leaves_all_data_unchanged(self):
        import copy
        plan, position = self.save_sample()
        before = self.store.export_backup()
        recorded = outcomes(plan)
        recorded[0]["status"] = None
        with self.assertRaises(StorageError):
            self.store.save_lesson_progress(plan["planning_date"], plan["plan_id"], recorded)
        self.assertEqual(self.store.export_backup(), before)
        bad = copy.deepcopy(before)
        bad["actual_progress"][0]["lessons"][0]["note"] = "x" * 301
        with self.assertRaises(StorageError):
            self.store.restore_backup(bad)
        self.assertEqual(self.store.export_backup(), before)

    def test_new_progress_cannot_replace_historical_whole_day(self):
        self.store.save_progress("2026-09-30", "Wednesday", "Completed", "Teacher confirmed original")
        before = self.store.export_backup()
        plan = sample_plan()
        with self.assertRaises(StorageError):
            self.store.save_day_plan(plan)
        with self.assertRaises(StorageError):
            self.store.save_lesson_progress(plan["planning_date"], plan["plan_id"], outcomes(plan))
        self.assertEqual(self.store.export_backup(), before)

    def test_additive_initialisation_preserves_preexisting_documents_and_history(self):
        self.store.save_document("teacher_profile", {"class_level": "5th Class", "pupil_count": 22})
        self.store.save_progress("2026-09-30", "Wednesday", "Partially completed", "Original teacher note")
        with self.connect(self.url) as connection:
            connection.execute("DROP TABLE lesson_progress")
            connection.execute("DROP TABLE day_plans")
        self.store.initialise(self.root / "missing.db")
        self.assertEqual(self.store.load_document("teacher_profile")["pupil_count"], 22)
        self.assertEqual(self.store.load_day("2026-09-30")["progress"]["notes"], "Original teacher note")
        self.assertIsNone(self.store.load_day("2026-09-30")["plan"])


if __name__ == "__main__":
    unittest.main()
