"""Run locally with a SQLite SQL adapter; CI also runs against real PostgreSQL."""
import json
import os
import sqlite3
import tempfile
import unittest
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from unittest.mock import patch
from urllib.parse import urlparse

import psycopg
from persistence import DOCUMENTS, Store, StorageError


class SQLiteAdapter:
    """Test-only adapter; production never uses this fallback."""
    def __init__(self, path):
        self.connection = sqlite3.connect(path, timeout=30)

    def __enter__(self):
        return self

    def __exit__(self, kind, value, traceback):
        try:
            if kind is None:
                self.connection.commit()
            else:
                self.connection.rollback()
        finally:
            self.connection.close()

    def execute(self, sql, params=()):
        if sql.startswith("SET LOCAL"):
            return self.connection.execute("SELECT 1")
        if "pg_advisory_xact_lock" in sql:
            self.connection.execute("BEGIN IMMEDIATE")
            return self.connection.execute("SELECT 1")
        sql = sql.replace(
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "INTEGER PRIMARY KEY AUTOINCREMENT",
        ).replace("%s", "?")
        return self.connection.execute(sql, params)


class StoreTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.legacy = self.root / "legacy.db"
        self.url = os.environ.get("TEST_DATABASE_URL", "test-only")
        if self.url != "test-only":
            parsed = urlparse(self.url)
            if parsed.hostname not in ("localhost", "127.0.0.1") or parsed.path != "/test_teacher_ai":
                raise RuntimeError("Integration tests only accept a local test_teacher_ai database")
            self.real_connect = psycopg.connect
            with self.real_connect(self.url) as connection:
                for table in [*DOCUMENTS, "actual_progress", "storage_migrations"]:
                    connection.execute(f"DROP TABLE IF EXISTS {table}")
            def connect(url, **kwargs):
                # The isolated CI localhost service has no TLS; production
                # continues to require it.
                kwargs["sslmode"] = "disable"
                return self.real_connect(url, **kwargs)
        else:
            def connect(url, **kwargs):
                return SQLiteAdapter(self.root / "remote.db")
        self.connect = connect
        self.patcher = patch("persistence.psycopg.connect", side_effect=connect)
        self.patcher.start()
        self.store = Store(self.url)
        self.store.initialise(self.legacy)

    def tearDown(self):
        self.patcher.stop()
        self.temp.cleanup()

    def create_legacy(self, invalid=False, dated=True):
        with sqlite3.connect(self.legacy) as connection:
            for table, column in DOCUMENTS.items():
                connection.execute(f"CREATE TABLE {table} (id INTEGER PRIMARY KEY, {column} TEXT)")
                value = "bad-json" if invalid and table == "planning_setup" else json.dumps({"value": table})
                connection.execute(f"INSERT INTO {table} VALUES (1, ?)", (value,))
            connection.execute("""
                CREATE TABLE actual_progress (
                    id INTEGER PRIMARY KEY, planning_day TEXT, subject TEXT,
                    lesson_topic TEXT, status TEXT, notes TEXT
                )
            """)
            if dated:
                connection.execute("ALTER TABLE actual_progress ADD COLUMN planning_date TEXT")
                connection.execute(
                    "INSERT INTO actual_progress VALUES (9, 'Wednesday', 'Full day', 'Daily teaching plan', "
                    "'Partially completed', 'Gaeilge missed', '2026-09-30')"
                )
            else:
                connection.execute(
                    "INSERT INTO actual_progress VALUES (9, 'Wednesday', 'Full day', 'Daily teaching plan', "
                    "'Partially completed', 'Gaeilge missed')"
                )

    def reset_migration(self):
        with self.connect(self.url) as connection:
            connection.execute("DELETE FROM storage_migrations")

    def test_all_four_areas_survive_fresh_store_and_runtime_loss(self):
        for name in DOCUMENTS:
            self.store.save_document(name, {"text": "Am Don Léamh", "count": 27})
        self.store.save_progress("2026-09-30", "Wednesday", "Partially completed", "English unfinished")
        # A redeployment has no old local file, only the same external database.
        fresh = Store(self.url)
        fresh.initialise(self.root / "new-runtime" / "missing.db")
        for name in DOCUMENTS:
            self.assertEqual(fresh.load_document(name), {"text": "Am Don Léamh", "count": 27})
        self.assertEqual(fresh.load_progress_history()[0]["notes"], "English unfinished")
        self.assertEqual(fresh.load_recent_progress()[0]["planning_date"], "2026-09-30")

    def test_progress_updates_one_date_and_corrections_reject_conflicts(self):
        self.assertFalse(self.store.save_progress("2026-09-30", "Wednesday", "Completed", "Maths done"))
        self.assertTrue(self.store.save_progress("2026-09-30", "Wednesday", "Not taught", "Assembly"))
        self.store.save_progress("2026-10-01", "Thursday", "Completed", "English done")
        history = self.store.load_progress_history()
        self.assertEqual(len(history), 2)
        self.assertFalse(self.store.correct_progress(history[0]["id"], "2026-10-01", "Thursday", "Completed", "conflict"))
        self.assertEqual(self.store.load_progress_history(), history)
        self.assertTrue(self.store.correct_progress(history[0]["id"], "2026-09-29", "Tuesday", "Partially completed", "corrected"))
        self.assertEqual(self.store.load_progress_history()[0]["notes"], "corrected")

    def test_concurrent_saves_do_not_duplicate_progress(self):
        def save(index):
            return self.store.save_progress("2026-09-30", "Wednesday", "Completed", str(index))
        with ThreadPoolExecutor(max_workers=4) as pool:
            list(pool.map(save, range(8)))
        self.assertEqual(len(self.store.load_progress_history()), 1)

    def test_migration_is_complete_once_and_does_not_overwrite_edits(self):
        self.create_legacy()
        self.reset_migration()
        self.store.initialise(self.legacy)
        for name in DOCUMENTS:
            self.assertEqual(self.store.load_document(name), {"value": name})
        self.assertEqual(len(self.store.load_progress_history()), 1)
        self.store.save_document("teacher_profile", {"value": "newer teacher edit"})
        self.store.initialise(self.legacy)
        self.assertEqual(self.store.load_document("teacher_profile"), {"value": "newer teacher edit"})
        self.assertEqual(len(self.store.load_progress_history()), 1)
        self.store.save_progress("2026-10-01", "Thursday", "Completed", "new record")
        self.assertEqual(len(self.store.load_progress_history()), 2)

    def test_legacy_undated_progress_is_preserved(self):
        self.create_legacy(dated=False)
        self.reset_migration()
        self.store.initialise(self.legacy)
        self.assertEqual(self.store.load_progress_history(), [])
        self.assertEqual(self.store.load_recent_progress()[0]["notes"], "Gaeilge missed")
        self.assertIsNone(self.store.load_recent_progress()[0]["planning_date"])

    def test_migration_rolls_back_all_data_on_invalid_legacy_json(self):
        self.create_legacy(invalid=True)
        self.reset_migration()
        with self.assertRaises(StorageError):
            self.store.initialise(self.legacy)
        self.assertEqual(self.store.load_document("teacher_profile"), {})
        with self.connect(self.url) as connection:
            self.assertIsNone(connection.execute("SELECT name FROM storage_migrations").fetchone())

    def test_nonempty_destination_is_never_overwritten_by_legacy(self):
        self.store.save_document("current_learning_position", {"Maths": "Subtraction"})
        self.create_legacy()
        self.reset_migration()
        self.store.initialise(self.legacy)
        self.assertEqual(self.store.load_document("current_learning_position"), {"Maths": "Subtraction"})
        self.assertEqual(self.store.load_document("teacher_profile"), {})

    def test_failure_is_safe_and_never_falls_back(self):
        with patch("persistence.psycopg.connect", side_effect=RuntimeError("password=VERY_PRIVATE")):
            with self.assertRaises(StorageError) as error:
                self.store.save_document("teacher_profile", {"new": "value"})
        self.assertNotIn("VERY_PRIVATE", str(error.exception))
        self.assertEqual(self.store.load_document("teacher_profile"), {})
        with self.assertRaises(StorageError):
            Store("")


if __name__ == "__main__":
    unittest.main()
