"""Run locally with a SQLite SQL adapter; CI also runs against real PostgreSQL."""
import json
from datetime import date
import os
import sqlite3
import tempfile
import unittest
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from unittest.mock import patch
from urllib.parse import urlparse

import psycopg
from persistence import DOCUMENTS, Store, StorageError
from fixtures import sample_plan, outcomes
from lesson_progress import EVIDENCE_MARKER


class SQLiteAdapter:
    """Test-only adapter; production never uses this fallback."""
    def __init__(self, path):
        self.connection = sqlite3.connect(path, timeout=30)

    def __enter__(self):
        return self

    def __exit__(self, kind, value, traceback):
        try:
            if kind is None:
                self.connection.commit()
            else:
                self.connection.rollback()
        finally:
            self.connection.close()

    def execute(self, sql, params=()):
        if sql.startswith("SET LOCAL"):
            return self.connection.execute("SELECT 1")
        if "pg_advisory_xact_lock" in sql:
            self.connection.execute("BEGIN IMMEDIATE")
            return self.connection.execute("SELECT 1")
        sql = sql.replace(
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "INTEGER PRIMARY KEY AUTOINCREMENT",
        ).replace("%s", "?")
        return self.connection.execute(sql, params)


class StoreTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.legacy = self.root / "legacy.db"
        self.url = os.environ.get("TEST_DATABASE_URL", "test-only")
        if self.url != "test-only":
            parsed = urlparse(self.url)
            if parsed.hostname not in ("localhost", "127.0.0.1") or parsed.path != "/test_teacher_ai":
                raise RuntimeError("Integration tests only accept a local test_teacher_ai database")
            self.real_connect = psycopg.connect
            with self.real_connect(self.url) as connection:
                for table in ["monthly_item_updates", "monthly_learning_items", "period_reviews", "carryover_items", "monthly_plans", "lesson_progress", "day_plans", *DOCUMENTS, "actual_progress", "storage_migrations"]:
                    connection.execute(f"DROP TABLE IF EXISTS {table}")
            def connect(url, **kwargs):
                # The isolated CI localhost service has no TLS; production
                # continues to require it.
                kwargs["sslmode"] = "disable"
                return self.real_connect(url, **kwargs)
        else:
            def connect(url, **kwargs):
                return SQLiteAdapter(self.root / "remote.db")
        self.connect = connect
        self.patcher = patch("persistence.psycopg.connect", side_effect=connect)
        self.patcher.start()
        self.store = Store(self.url)
        self.store.initialise(self.legacy)

    def tearDown(self):
        self.patcher.stop()
        self.temp.cleanup()

    def test_quality_metadata_backup_and_stale_context_guard(self):
        from planning_quality import digest
        self.store.save_monthly_plan(self.monthly(), True)
        plan = sample_plan('2026-09-30')
        context = self.store.planning_quality_context('2026-09-30')
        plan['monthly_plan'] = {k: context['monthly_plan'][k] for k in ('id','title','start_date','end_date')}
        plan['planning_quality'] = dict(version=1, state='Pass', context_digest=digest(context), revision_count=0, extra_ai_calls=1)
        before = self.store.export_backup()
        self.store.save_day_plan(plan)
        after = self.store.export_backup()
        self.assertEqual(after['day_plans'][0]['planning_quality'], plan['planning_quality'])
        for key in before:
            if key != 'day_plans': self.assertEqual(before[key], after[key])
        self.store.save_document('current_learning_position', {'English':'Teacher corrected the stopping point'})
        with self.assertRaises(StorageError): self.store.save_day_plan(plan)
        self.assertEqual(self.store.load_day('2026-09-30')['plan'], plan)
        for state in ('Unchecked','Blocked','Revise'):
            plan['planning_quality']['state'] = state
            with self.assertRaises(StorageError): self.store.save_day_plan(plan)
        backup = self.store.export_backup()
        with patch('persistence.psycopg.connect', side_effect=lambda *a, **k: SQLiteAdapter(self.root / 'quality-restored.db')):
            restored = Store('test-only'); restored.initialise(self.root / 'absent.db'); restored.restore_backup(backup)
            self.assertEqual(restored.load_day('2026-09-30')['plan'], backup['day_plans'][0])

    def test_quality_context_includes_prior_progress_not_future(self):
        self.store.save_progress('2026-09-30','Wednesday','Partially completed','English final activity unfinished')
        self.store.save_progress('2026-10-02','Friday','Not taught','Future record')
        context = self.store.planning_quality_context('2026-10-01')
        self.assertEqual([r['planning_date'] for r in context['recent_progress']], ['2026-09-30'])

    def test_review_confirmation_date_guard_and_concurrent_once(self):
        self.store.save_monthly_plan(self.monthly(), True)
        monthly = self.monthly("oct", "2026-10-01", "2026-10-31")
        self.store.save_monthly_plan(monthly, True)
        with self.assertRaises(StorageError):
            self.store.save_period_review(monthly, "2026-10-01", [])
        with self.assertRaises(StorageError):
            self.store.save_period_review(monthly, "2026-09-30", [], True)
        def save(_):
            try:
                self.store.save_period_review(monthly, "2026-10-01", [], True)
                return True
            except StorageError:
                return False
        with ThreadPoolExecutor(max_workers=4) as pool:
            self.assertEqual(sum(pool.map(save, range(4))), 1)
        self.assertTrue(self.store.carryover_context(monthly, "2026-10-02")["review"]["nothing_selected"])

    def test_carryover_backup_roundtrip(self):
        self.carry_setup()
        backup = self.store.export_backup()
        with self.store._connection() as connection:
            for table in ("period_reviews", "carryover_items", "monthly_plans"):
                connection.execute(f"DELETE FROM {table}")
        self.assertTrue(self.store.restore_backup(backup))
        self.assertEqual(self.store.list_carryover(), backup["carryover_items"])
        monthly = self.store.select_monthly_plan("2026-10-01")
        self.assertIsNotNone(self.store.carryover_context(monthly, "2026-10-02")["review"])

    def carry_setup(self):
        self.store.save_monthly_plan(self.monthly(), True)
        monthly = self.monthly("oct", "2026-10-01", "2026-10-31")
        self.store.save_monthly_plan(monthly, True)
        item = {"id": "carry-english", "period_id": "oct", "subject": "English", "learning": "Finish final activity", "evidence": "30 September partial", "created_date": "2026-10-01", "state": "outstanding"}
        self.store.save_period_review(monthly, "2026-10-01", [item], True)
        return monthly, item

    def test_carryover_review_is_durable_once_and_nothing_is_explicit(self):
        monthly, item = self.carry_setup()
        context = self.store.carryover_context(monthly, "2026-10-01")
        self.assertEqual(context["previous"]["id"], "sep")
        self.assertFalse(context["review"]["nothing_selected"])
        with self.assertRaises(StorageError):
            self.store.save_period_review(monthly, "2026-10-01", [], True)
        self.assertEqual(len(self.store.list_carryover()), 1)
        self.assertEqual(self.store.list_carryover("2026-09-30"), [])

    def test_carryover_link_completion_partial_correction_and_manual_removal(self):
        monthly, item = self.carry_setup()
        plan = sample_plan("2026-10-01")
        plan["lessons"][1]["carryover_ids"] = [item["id"]]
        self.store.save_day_plan(plan)
        recorded = outcomes(plan)
        recorded[1]["completed_carryover_ids"] = []
        self.store.save_lesson_progress(plan["planning_date"], plan["plan_id"], recorded)
        self.assertEqual(self.store.list_carryover()[0]["state"], "outstanding")
        recorded[1].update(status="Completed", completed_carryover_ids=[item["id"]])
        self.store.save_lesson_progress(plan["planning_date"], plan["plan_id"], recorded)
        self.assertEqual(self.store.list_carryover()[0]["state"], "completed")
        row = self.store.load_progress_history()[0]
        recorded[1].update(status="Not taught", completed_carryover_ids=[])
        self.store.correct_lesson_progress(row["id"], "2026-10-01", recorded)
        self.assertEqual(self.store.list_carryover()[0]["state"], "outstanding")
        self.store.set_carryover_state(item["id"], "completed")
        self.assertEqual(self.store.list_carryover()[0]["state"], "completed")
        self.store.set_carryover_state(item["id"], "removed")
        self.assertEqual(self.store.list_carryover()[0]["state"], "removed")
        self.store.set_carryover_state(item["id"], "outstanding")
        self.assertEqual(self.store.list_carryover()[0]["state"], "outstanding")

    def test_carryover_cannot_close_from_partial_or_forged_link(self):
        monthly, item = self.carry_setup()
        plan = sample_plan("2026-10-01")
        plan["lessons"][1]["carryover_ids"] = [item["id"]]
        self.store.save_day_plan(plan)
        recorded = outcomes(plan)
        recorded[1]["completed_carryover_ids"] = [item["id"]]
        with self.assertRaises(StorageError):
            self.store.save_lesson_progress(plan["planning_date"], plan["plan_id"], recorded)
        self.assertEqual(self.store.load_progress_history(), [])
        forged = sample_plan("2026-10-02")
        forged["lessons"][0]["carryover_ids"] = ["invented"]
        with self.assertRaises(StorageError):
            self.store.save_day_plan(forged)

    def monthly(self, id="sep", start="2026-09-01", end="2026-09-30"):
        return {"id": id, "title": id, "source_filename": "October 2030.docx",
                "plan_text": "September teaching", "start_date": start, "end_date": end}

    def test_monthly_source_survives_progress_and_correction(self):
        plan = sample_plan()
        plan["monthly_plan"] = {"id": "sep", "title": "September 2026 Monthly Plan", "start_date": "2026-09-01", "end_date": "2026-09-30"}
        self.store.save_day_plan(plan)
        self.store.save_lesson_progress(plan["planning_date"], plan["plan_id"], outcomes(plan))
        self.assertEqual(self.store.load_day(plan["planning_date"])["plan"]["monthly_plan"], plan["monthly_plan"])
        record = self.store.load_progress_history()[0]
        self.store.correct_lesson_progress(record["id"], "2026-09-29", outcomes(plan))
        self.assertEqual(self.store.load_day("2026-09-29")["plan"]["monthly_plan"], plan["monthly_plan"])

    def test_monthly_boundary_and_explicit_confirmation(self):
        with self.assertRaises(StorageError):
            self.store.save_monthly_plan(self.monthly())
        self.store.save_monthly_plan(self.monthly(), True)
        self.store.save_monthly_plan(self.monthly("oct", "2026-10-01", "2026-10-31"), True)
        self.assertEqual(self.store.select_monthly_plan("2026-09-30")["id"], "sep")
        self.assertEqual(self.store.select_monthly_plan("2026-10-01")["id"], "oct")
        self.assertIsNone(self.store.select_monthly_plan("2027-09-30"))
        self.assertIsNone(self.store.select_monthly_plan("2026-11-01"))

    def test_monthly_overlap_and_edit_are_atomic(self):
        self.store.save_monthly_plan(self.monthly(), True)
        for start, end in (("2026-09-30", "2026-10-31"), ("2026-08-01", "2026-09-01"), ("2026-09-04", "2026-09-05")):
            with self.assertRaises(StorageError):
                self.store.save_monthly_plan(self.monthly("other", start, end), True)
        changed = self.monthly()
        changed["title"] = "Updated September"
        self.store.save_monthly_plan(changed, True)
        self.assertEqual(len(self.store.list_monthly_plans()), 1)

    def test_concurrent_overlapping_monthly_saves_allow_only_one(self):
        def save(number):
            try:
                self.store.save_monthly_plan(self.monthly(str(number)), True)
                return True
            except StorageError:
                return False
        with ThreadPoolExecutor(max_workers=4) as pool:
            results = list(pool.map(save, range(4)))
        self.assertEqual(sum(results), 1)
        self.assertEqual(len(self.store.list_monthly_plans()), 1)

    def test_monthly_backup_roundtrip_and_invalid_overlap_rejected(self):
        self.store.save_monthly_plan(self.monthly(), True)
        backup = self.store.export_backup()
        destination = Store(self.url)
        # Clear only the isolated test database.
        with self.connect(self.url) as connection:
            connection.execute("DELETE FROM monthly_plans")
        self.assertTrue(destination.restore_backup(backup))
        self.assertEqual(destination.list_monthly_plans(), backup["monthly_plans"])
        backup["monthly_plans"].append(self.monthly("overlap"))
        with self.assertRaises(StorageError):
            destination.restore_backup(backup)
        self.assertEqual(len(destination.list_monthly_plans()), 1)

    def test_existing_monthly_migration_retains_text_and_never_guesses_dates(self):
        original = {"monthly_plan_text": "September 2026 existing text", "yearly_plan_text": "year"}
        self.store.save_document("planning_setup", original)
        with self.connect(self.url) as connection:
            connection.execute("DELETE FROM storage_migrations WHERE name = %s", ("dated_monthly_v1",))
        self.store.initialise(self.legacy)
        pending = self.store.list_monthly_plans()[0]
        self.assertIsNone(pending["start_date"])
        self.assertEqual(pending["plan_text"], original["monthly_plan_text"])
        self.assertIsNone(self.store.select_monthly_plan("2026-09-30"))
        pending.update(start_date="2026-09-01", end_date="2026-09-30")
        self.store.save_monthly_plan(pending, True)
        self.store.initialise(self.legacy)
        self.assertEqual(self.store.list_monthly_plans()[0]["start_date"], "2026-09-01")
        self.assertEqual(self.store.load_document("planning_setup"), original)

    def create_legacy(self, invalid=False, dated=True):
        with sqlite3.connect(self.legacy) as connection:
            for table, column in DOCUMENTS.items():
                connection.execute(f"CREATE TABLE {table} (id INTEGER PRIMARY KEY, {column} TEXT)")
                value = "bad-json" if invalid and table == "planning_setup" else json.dumps({"value": table})
                connection.execute(f"INSERT INTO {table} VALUES (1, ?)", (value,))
            connection.execute("""
                CREATE TABLE actual_progress (
                    id INTEGER PRIMARY KEY, planning_day TEXT, subject TEXT,
                    lesson_topic TEXT, status TEXT, notes TEXT
                )
            """)
            if dated:
                connection.execute("ALTER TABLE actual_progress ADD COLUMN planning_date TEXT")
                connection.execute(
                    "INSERT INTO actual_progress VALUES (9, 'Wednesday', 'Full day', 'Daily teaching plan', "
                    "'Partially completed', 'Gaeilge missed', '2026-09-30')"
                )
            else:
                connection.execute(
                    "INSERT INTO actual_progress VALUES (9, 'Wednesday', 'Full day', 'Daily teaching plan', "
                    "'Partially completed', 'Gaeilge missed')"
                )

    def reset_migration(self):
        with self.connect(self.url) as connection:
            connection.execute("DELETE FROM storage_migrations")

    def test_all_four_areas_survive_fresh_store_and_runtime_loss(self):
        for name in DOCUMENTS:
            self.store.save_document(name, {"text": "Am Don Léamh", "count": 27})
        self.store.save_progress("2026-09-30", "Wednesday", "Partially completed", "English unfinished")
        # A redeployment has no old local file, only the same external database.
        fresh = Store(self.url)
        fresh.initialise(self.root / "new-runtime" / "missing.db")
        for name in DOCUMENTS:
            self.assertEqual(fresh.load_document(name), {"text": "Am Don Léamh", "count": 27})
        self.assertEqual(fresh.load_progress_history()[0]["notes"], "English unfinished")
        self.assertEqual(fresh.load_recent_progress()[0]["planning_date"], "2026-09-30")

    def test_progress_updates_one_date_and_corrections_reject_conflicts(self):
        self.assertFalse(self.store.save_progress("2026-09-30", "Wednesday", "Completed", "Maths done"))
        self.assertTrue(self.store.save_progress("2026-09-30", "Wednesday", "Not taught", "Assembly"))
        self.store.save_progress("2026-10-01", "Thursday", "Completed", "English done")
        history = self.store.load_progress_history()
        self.assertEqual(len(history), 2)
        self.assertFalse(self.store.correct_progress(history[0]["id"], "2026-10-01", "Thursday", "Completed", "conflict"))
        self.assertEqual(self.store.load_progress_history(), history)
        self.assertTrue(self.store.correct_progress(history[0]["id"], "2026-09-29", "Tuesday", "Partially completed", "corrected"))
        self.assertEqual(self.store.load_progress_history()[0]["notes"], "corrected")

    def test_concurrent_saves_do_not_duplicate_progress(self):
        def save(index):
            return self.store.save_progress("2026-09-30", "Wednesday", "Completed", str(index))
        with ThreadPoolExecutor(max_workers=4) as pool:
            list(pool.map(save, range(8)))
        self.assertEqual(len(self.store.load_progress_history()), 1)

    def test_migration_is_complete_once_and_does_not_overwrite_edits(self):
        self.create_legacy()
        self.reset_migration()
        self.store.initialise(self.legacy)
        for name in DOCUMENTS:
            self.assertEqual(self.store.load_document(name), {"value": name})
        self.assertEqual(len(self.store.load_progress_history()), 1)
        self.store.save_document("teacher_profile", {"value": "newer teacher edit"})
        self.store.initialise(self.legacy)
        self.assertEqual(self.store.load_document("teacher_profile"), {"value": "newer teacher edit"})
        self.assertEqual(len(self.store.load_progress_history()), 1)
        self.store.save_progress("2026-10-01", "Thursday", "Completed", "new record")
        self.assertEqual(len(self.store.load_progress_history()), 2)

    def test_legacy_undated_progress_is_preserved(self):
        self.create_legacy(dated=False)
        self.reset_migration()
        self.store.initialise(self.legacy)
        self.assertEqual(self.store.load_progress_history(), [])
        self.assertEqual(self.store.load_recent_progress()[0]["notes"], "Gaeilge missed")
        self.assertIsNone(self.store.load_recent_progress()[0]["planning_date"])

    def test_migration_rolls_back_all_data_on_invalid_legacy_json(self):
        self.create_legacy(invalid=True)
        self.reset_migration()
        with self.assertRaises(StorageError):
            self.store.initialise(self.legacy)
        self.assertEqual(self.store.load_document("teacher_profile"), {})
        with self.connect(self.url) as connection:
            self.assertIsNone(connection.execute("SELECT name FROM storage_migrations").fetchone())

    def test_nonempty_destination_is_never_overwritten_by_legacy(self):
        self.store.save_document("current_learning_position", {"Maths": "Subtraction"})
        self.create_legacy()
        self.reset_migration()
        self.store.initialise(self.legacy)
        self.assertEqual(self.store.load_document("current_learning_position"), {"Maths": "Subtraction"})
        self.assertEqual(self.store.load_document("teacher_profile"), {})

    def test_failure_is_safe_and_never_falls_back(self):
        with patch("persistence.psycopg.connect", side_effect=RuntimeError("password=VERY_PRIVATE")):
            with self.assertRaises(StorageError) as error:
                self.store.save_document("teacher_profile", {"new": "value"})
        self.assertNotIn("VERY_PRIVATE", str(error.exception))
        self.assertEqual(self.store.load_document("teacher_profile"), {})
        with self.assertRaises(StorageError):
            Store("")

    def test_backup_roundtrip_and_nonempty_restore_refused(self):
        backup = {
            "format_version": 1,
            "teacher_profile": {"class_level": "5th Class"},
            "planning_setup": {"monthly_plan_text": "Irish: Mé Féin"},
            "current_learning_position": {"Maths": "Subtraction"},
            "actual_progress": [{
                "planning_day": "Wednesday", "subject": "Full day",
                "lesson_topic": "Daily teaching plan", "status": "Partially completed",
                "notes": "Gaeilge missed", "planning_date": "2026-09-30",
            }],
        }
        self.assertTrue(self.store.restore_backup(backup))
        exported = self.store.export_backup()
        for name in DOCUMENTS:
            self.assertEqual(exported[name], backup[name])
        self.assertEqual(exported["actual_progress"][0]["notes"], "Gaeilge missed")
        self.assertFalse(self.store.restore_backup(backup))
        self.assertEqual(self.store.export_backup(), exported)

    def test_invalid_backup_does_not_write_partial_data(self):
        with self.assertRaises(StorageError):
            self.store.restore_backup({
                "format_version": 1,
                "teacher_profile": {"value": "must not be saved"},
                "planning_setup": {}, "current_learning_position": {},
                "actual_progress": [{"planning_day": "Wednesday", "subject": "Full day",
                    "status": "Completed", "planning_date": "not-a-date"}],
            })
        self.assertEqual(self.store.load_document("teacher_profile"), {})

    def save_sample(self, day="2026-09-30"):
        plan = sample_plan(day)
        self.store.save_day_plan(plan)
        position = self.store.save_lesson_progress(day, plan["plan_id"], outcomes(plan))
        return plan, position

    def test_lesson_snapshot_and_learning_survive_runtime_loss_and_retry(self):
        self.store.save_document("current_learning_position", {"Maths": "Addition completed", "Other": "Friday Art"})
        plan, position = self.save_sample()
        fresh = Store(self.url)
        fresh.initialise(self.root / "missing-again.db")
        self.assertEqual(fresh.load_day(plan["planning_date"])["progress"]["lessons"], outcomes(plan))
        self.assertEqual(fresh.load_recent_progress()[0]["lessons"], outcomes(plan))
        self.assertEqual(fresh.load_document("current_learning_position"), position)
        self.assertIn("Addition completed", position["Maths"])
        self.assertEqual(position["Other"], "Friday Art")
        self.assertEqual(fresh.save_lesson_progress(plan["planning_date"], plan["plan_id"], outcomes(plan)), position)
        self.assertEqual(len(fresh.load_progress_history()), 1)

    def test_plan_regeneration_rejects_stale_lesson_ids_and_preserves_saved_progress(self):
        first = sample_plan()
        self.store.save_day_plan(first)
        replacement = sample_plan()
        self.store.save_day_plan(replacement)
        with self.assertRaises(StorageError):
            self.store.save_lesson_progress(first["planning_date"], first["plan_id"], outcomes(first))
        self.assertEqual(self.store.load_progress_history(), [])
        self.store.save_lesson_progress(replacement["planning_date"], replacement["plan_id"], outcomes(replacement))
        with self.assertRaises(StorageError):
            self.store.save_day_plan(sample_plan())
        with self.assertRaises(StorageError):
            self.store.save_progress("2026-09-30", "Wednesday", "Completed", "Cannot replace lessons")
        tampered = outcomes(replacement)
        tampered[0]["learning_intention"] = "Finish the whole unit"
        with self.assertRaises(StorageError):
            self.store.save_lesson_progress(replacement["planning_date"], replacement["plan_id"], tampered)
        self.assertEqual(self.store.load_progress_history()[0]["lessons"], outcomes(replacement))

    def test_lessons_and_learning_rollback_together_if_update_fails(self):
        plan = sample_plan()
        self.store.save_day_plan(plan)
        self.store.save_document("current_learning_position", {"English": "Known starting position"})
        with patch.object(Store, "_project_position", side_effect=RuntimeError("private connection string")):
            with self.assertRaises(StorageError) as error:
                self.store.save_lesson_progress(plan["planning_date"], plan["plan_id"], outcomes(plan))
        self.assertNotIn("private", str(error.exception))
        self.assertEqual(self.store.load_progress_history(), [])
        self.assertEqual(self.store.load_document("current_learning_position"), {"English": "Known starting position"})

    def test_concurrent_lesson_saves_keep_one_day_and_matching_learning(self):
        plan = sample_plan()
        self.store.save_day_plan(plan)
        def save(index):
            recorded = outcomes(plan)
            recorded[1]["note"] = f"Unfinished detail {index}"
            return self.store.save_lesson_progress(plan["planning_date"], plan["plan_id"], recorded)
        with ThreadPoolExecutor(max_workers=4) as pool:
            list(pool.map(save, range(8)))
        history = self.store.load_progress_history()
        self.assertEqual(len(history), 1)
        self.assertIn(history[0]["lessons"][1]["note"], self.store.load_document("current_learning_position")["English"])

    def test_correction_moves_date_and_removes_obsolete_outcomes(self):
        plan, old_position = self.save_sample()
        row = self.store.load_progress_history()[0]
        changed = outcomes(plan)
        changed[1].update(status="Completed", note="Finished the final activity")
        updated = self.store.correct_lesson_progress(row["id"], "2026-09-29", changed)
        self.assertNotIn("didn't finish", updated["English"])
        self.assertNotIn("2026-09-30", updated["English"])
        self.assertIn("2026-09-29", updated["English"])
        self.assertIn("Finished the final activity", updated["English"])
        self.assertEqual(self.store.load_day("2026-09-29")["plan"]["lessons"], changed)
        self.store.save_progress("2026-10-01", "Thursday", "Completed", "Legacy")
        before = self.store.export_backup()
        self.assertIsNone(self.store.correct_lesson_progress(row["id"], "2026-10-01", changed))
        self.assertEqual(self.store.export_backup(), before)

    def test_repeated_subjects_are_distinct_and_notes_override_planned_learning(self):
        import copy
        plan = sample_plan()
        second = copy.deepcopy(plan["lessons"][1])
        second.update(lesson_id="second-english", subject="Reading", topic="Reading comprehension", time="13:50–14:20",
                      learning_intention="Explain the character's motive.")
        plan["lessons"].append(second)
        self.store.save_day_plan(plan)
        recorded = outcomes(plan)
        recorded[-1].update(status="Completed", note="Changed lesson: practised spelling instead; no reading taught")
        position = self.store.save_lesson_progress(plan["planning_date"], plan["plan_id"], recorded)
        self.assertIn("Narrative openings", position["English"])
        self.assertIn("Reading comprehension", position["English"])
        self.assertIn("authoritative): Changed lesson", position["English"])
        self.assertIn("no reading taught", position["English"])
        self.assertEqual(len(self.store.load_progress_history()[0]["lessons"]), 4)

    def test_new_backup_roundtrip_preserves_plans_and_lesson_snapshots(self):
        plan, position = self.save_sample()
        backup = self.store.export_backup()
        self.assertEqual(backup["format_version"], 5)
        with self.connect(self.url) as connection:
            for table in ["lesson_progress", "day_plans", "actual_progress", *DOCUMENTS]:
                connection.execute(f"DELETE FROM {table}")
        self.assertTrue(self.store.restore_backup(backup))
        restored = self.store.load_progress_history()[0]
        self.assertEqual(restored["lessons"], outcomes(plan))
        self.assertEqual(restored["plan_id"], plan["plan_id"])
        self.assertEqual(self.store.load_day(plan["planning_date"])["plan"]["plan_id"], plan["plan_id"])
        self.assertEqual(self.store.load_document("current_learning_position"), position)
        self.assertFalse(self.store.restore_backup(backup))

    def test_invalid_lesson_or_backup_leaves_all_data_unchanged(self):
        import copy
        plan, position = self.save_sample()
        before = self.store.export_backup()
        recorded = outcomes(plan)
        recorded[0]["status"] = None
        with self.assertRaises(StorageError):
            self.store.save_lesson_progress(plan["planning_date"], plan["plan_id"], recorded)
        self.assertEqual(self.store.export_backup(), before)
        bad = copy.deepcopy(before)
        bad["actual_progress"][0]["lessons"][0]["note"] = "x" * 301
        with self.assertRaises(StorageError):
            self.store.restore_backup(bad)
        self.assertEqual(self.store.export_backup(), before)

    def test_new_progress_cannot_replace_historical_whole_day(self):
        self.store.save_progress("2026-09-30", "Wednesday", "Completed", "Teacher confirmed original")
        before = self.store.export_backup()
        plan = sample_plan()
        with self.assertRaises(StorageError):
            self.store.save_day_plan(plan)
        with self.assertRaises(StorageError):
            self.store.save_lesson_progress(plan["planning_date"], plan["plan_id"], outcomes(plan))
        self.assertEqual(self.store.export_backup(), before)

    def test_additive_initialisation_preserves_preexisting_documents_and_history(self):
        self.store.save_document("teacher_profile", {"class_level": "5th Class", "pupil_count": 22})
        self.store.save_progress("2026-09-30", "Wednesday", "Partially completed", "Original teacher note")
        with self.connect(self.url) as connection:
            connection.execute("DROP TABLE lesson_progress")
            connection.execute("DROP TABLE day_plans")
        self.store.initialise(self.root / "missing.db")
        self.assertEqual(self.store.load_document("teacher_profile")["pupil_count"], 22)
        self.assertEqual(self.store.load_day("2026-09-30")["progress"]["notes"], "Original teacher note")
        self.assertIsNone(self.store.load_day("2026-09-30")["plan"])


    def learning_setup(self):
        from monthly_learning import fingerprint
        monthly = self.monthly()
        self.store.save_monthly_plan(monthly, True)
        items = [dict(id=f'item-{n}', monthly_plan_id=monthly['id'], subject='History', description=f'History aspect {n}', source=monthly['plan_text'], fingerprint=fingerprint(monthly['plan_text']), type=kind, archived=False) for n, kind in enumerate(['discrete', 'discrete', 'discrete', 'broad'])]
        self.store.save_learning_items(monthly, items)
        plan = sample_plan()
        plan['monthly_plan'] = {k: monthly[k] for k in ('id', 'title', 'start_date', 'end_date')}
        plan['lessons'][1]['monthly_item_links'] = [dict(item_id=i['id'], coverage=i['description']) for i in items]
        self.store.save_day_plan(plan)
        return monthly, items, plan

    def test_item_mixed_partial_exact_remainder_and_correction(self):
        monthly, items, plan = self.learning_setup()
        recorded = outcomes(plan)
        recorded[1]['item_updates'] = [dict(item_id=i['id'], status='Completed' if n < 3 else 'In progress', remaining='' if n < 3 else 'final immigrant-letter activity', evidence='teacher accepted item evidence', confirmed_complete=n < 3) for n, i in enumerate(items)]
        self.store.save_lesson_progress(plan['planning_date'], plan['plan_id'], recorded)
        current = {i['id']: i for i in self.store.list_learning_items()}
        self.assertEqual(sum(i['status'] == 'Completed' for i in current.values()), 3)
        self.assertEqual(current['item-3']['remaining'], 'final immigrant-letter activity')
        self.assertIn('final immigrant-letter activity', self.store.load_document('current_learning_position')['SESE'])
        recorded[1].update(status='Not taught', item_updates=[])
        self.store.correct_lesson_progress(self.store.load_progress_history()[0]['id'], '2026-09-30', recorded)
        self.assertTrue(all(i['status'] == 'Not started' for i in self.store.list_learning_items()))

    def test_completed_lesson_never_finishes_broad_or_discrete_item(self):
        monthly, items, plan = self.learning_setup()
        recorded = outcomes(plan)
        recorded[1].update(status='Completed', note='')
        self.store.save_lesson_progress(plan['planning_date'], plan['plan_id'], recorded)
        self.assertTrue(all(i['status'] == 'In progress' for i in self.store.list_learning_items()))

    def test_unconfirmed_completion_rolls_back_day_and_learning(self):
        monthly, items, plan = self.learning_setup()
        recorded = outcomes(plan)
        recorded[1]['item_updates'] = [dict(item_id='item-0', status='Completed', remaining='', evidence='AI suggestion', confirmed_complete=False)]
        before = self.store.export_backup()
        with self.assertRaises(StorageError):
            self.store.save_lesson_progress(plan['planning_date'], plan['plan_id'], recorded)
        self.assertEqual(before, self.store.export_backup())

    def test_manual_item_correction_preserved_until_new_evidence(self):
        monthly, items, plan = self.learning_setup()
        self.store.correct_learning_item('item-0', 'Completed', '', 'resolved separately', True)
        self.store.save_lesson_progress(plan['planning_date'], plan['plan_id'], outcomes(plan))
        self.assertEqual(next(i for i in self.store.list_learning_items() if i['id'] == 'item-0')['status'], 'Completed')
        self.store.correct_learning_item('item-0', 'In progress', 'last letter still unfinished', 'correction', False)
        self.assertEqual(next(i for i in self.store.list_learning_items() if i['id'] == 'item-0')['remaining'], 'last letter still unfinished')

    def test_learning_ids_edit_archive_restore_and_stale_edit_guard(self):
        monthly, items, plan = self.learning_setup()
        current = self.store.list_learning_items()
        current[0]['description'] = 'Corrected wording'
        self.store.save_learning_items(monthly, current)
        with self.assertRaises(StorageError):
            self.store.save_learning_items(monthly, current)
        newer = self.store.list_learning_items()
        newer[0]['archived'] = True
        self.store.save_learning_items(monthly, newer)
        self.assertTrue(self.store.list_learning_items()[0]['archived'])
        newer = self.store.list_learning_items()
        newer[0]['archived'] = False
        self.store.save_learning_items(monthly, newer)
        self.assertEqual(self.store.load_day('2026-09-30')['plan']['lessons'][1]['monthly_item_links'][0]['item_id'], 'item-0')

    def test_item_link_validation_no_unknown_or_completed(self):
        monthly, items, plan = self.learning_setup()
        plan['lessons'][1]['monthly_item_links'][0]['item_id'] = 'invented'
        with self.assertRaises(StorageError):
            self.store.save_day_plan(plan)
        plan['lessons'][1]['monthly_item_links'][0]['item_id'] = 'item-0'
        self.store.correct_learning_item('item-0', 'Completed', '', 'whole item confirmed', True)
        plan['planning_date'] = date.today().isoformat()
        with self.assertRaises(StorageError):
            self.store.save_day_plan(plan)

    def test_shared_carryover_status_completion_remove_and_duplicate_guard(self):
        monthly, items, plan = self.learning_setup()
        next_month = self.monthly('oct', '2026-10-01', '2026-10-31')
        self.store.save_monthly_plan(next_month, True)
        carry = dict(id='shared', period_id='oct', subject='History', learning='History aspect 0', evidence='unfinished', created_date='2026-10-01', state='outstanding', monthly_item_id='item-0')
        self.store.save_period_review(next_month, '2026-10-01', [carry], True)
        self.store.set_carryover_state('shared', 'removed')
        self.assertEqual(self.store.list_learning_items()[0]['status'], 'Not started')
        self.store.set_carryover_state('shared', 'completed')
        self.assertEqual(self.store.list_learning_items()[0]['status'], 'Completed')
        self.store.correct_learning_item('item-0', 'In progress', 'unfinished final step', 'teacher correction', False)
        self.assertEqual(self.store.list_carryover()[0]['state'], 'outstanding')
        self.assertEqual(self.store.list_carryover()[0]['learning'], 'unfinished final step')
        november = self.monthly('nov', '2026-11-01', '2026-11-30')
        self.store.save_monthly_plan(november, True)
        with self.assertRaises(StorageError):
            self.store.save_period_review(november, '2026-11-01', [{**carry, 'id': 'duplicate', 'period_id': 'nov', 'created_date': '2026-11-01'}], True)


    def regroup_bundle(self, monthly, items):
        backup = self.store.export_backup()
        raw = backup['monthly_learning_items']
        desired = [{**i, 'archived': True} if i['id'] in ('item-0', 'item-1') else i for i in raw]
        desired.append({**items[0], 'id': 'replacement', 'description': 'Reviewed combined scope', 'replacement_from': ['item-0', 'item-1']})
        return dict(monthly_plan_id=monthly['id'], expected_items=self.store.list_learning_items(monthly['id']), expected_updates=backup['monthly_item_updates'], expected_carryover=backup['carryover_items'], items=desired)

    def test_reviewed_regrouping_preserves_history_and_never_copies_completion(self):
        monthly, items, plan = self.learning_setup()
        self.store.correct_learning_item('item-0', 'Completed', '', 'whole old scope completed', True)
        before = self.store.export_backup()
        self.store.apply_reviewed_regrouping(monthly, self.regroup_bundle(monthly, items), True)
        after = self.store.export_backup()
        self.assertEqual(before['monthly_item_updates'], after['monthly_item_updates'])
        self.assertEqual(before['day_plans'], after['day_plans'])
        self.assertEqual(next(i for i in self.store.list_learning_items() if i['id'] == 'replacement')['status'], 'Not started')
        self.assertTrue(next(i for i in self.store.list_learning_items() if i['id'] == 'item-0')['archived'])
        # Existing day-plan snapshots remain recordable against their original IDs.
        self.store.save_lesson_progress(plan['planning_date'], plan['plan_id'], outcomes(plan))
        self.assertEqual(self.store.load_progress_history()[0]['lessons'][1]['monthly_item_links'], plan['lessons'][1]['monthly_item_links'])

    def test_regrouping_stale_progress_source_tampering_and_repeat_are_atomic(self):
        monthly, items, plan = self.learning_setup()
        bundle = self.regroup_bundle(monthly, items)
        self.store.correct_learning_item('item-0', 'In progress', 'last part', 'new note', False)
        before = self.store.export_backup()
        with self.assertRaises(StorageError):
            self.store.apply_reviewed_regrouping(monthly, bundle, True)
        self.assertEqual(before, self.store.export_backup())
        bundle = self.regroup_bundle(monthly, items)
        bundle['items'][0]['source'] = 'changed quote'
        with self.assertRaises(StorageError):
            self.store.apply_reviewed_regrouping(monthly, bundle, True)
        self.assertEqual(before, self.store.export_backup())
        bundle = self.regroup_bundle(monthly, items)
        self.store.apply_reviewed_regrouping(monthly, bundle, True)
        saved = self.store.export_backup()
        with self.assertRaises(StorageError):
            self.store.apply_reviewed_regrouping(monthly, bundle, True)
        self.assertEqual(saved, self.store.export_backup())

    def test_regrouping_carryover_uses_shared_replacement_without_outcome_transfer(self):
        monthly, items, plan = self.learning_setup()
        october = self.monthly('oct', '2026-10-01', '2026-10-31')
        self.store.save_monthly_plan(october, True)
        carry = dict(id='shared', monthly_item_id='item-0', period_id='oct', subject='History', learning='old scope', evidence='teacher confirms', created_date='2026-10-01', state='outstanding')
        self.store.save_period_review(october, '2026-10-01', [carry], True)
        self.store.apply_reviewed_regrouping(monthly, self.regroup_bundle(monthly, items), True)
        self.assertEqual(self.store.list_carryover()[0]['monthly_item_id'], 'replacement')
        self.assertEqual(self.store.list_carryover()[0]['state'], 'outstanding')
        self.assertEqual(next(i for i in self.store.list_learning_items() if i['id']=='replacement')['status'], 'Not started')

    def test_clarification_blocks_new_links_and_display_edits_keep_exact_source(self):
        from monthly_learning import display_wording
        monthly, items, plan = self.learning_setup()
        edited = self.store.list_learning_items()
        source = edited[0]['source']
        edited[0].update(requires_clarification=True, display_correction='Teacher-corrected name')
        self.store.save_learning_items(monthly, edited)
        item = self.store.list_learning_items()[0]
        self.assertEqual(display_wording(item), 'Teacher-corrected name')
        self.assertEqual(item['source'], source)
        with self.assertRaises(StorageError):
            self.store.save_day_plan(plan)
        edited = self.store.list_learning_items()
        edited[0]['requires_clarification'] = False
        self.store.save_learning_items(monthly, edited)
        self.store.save_day_plan(plan)

    def test_regrouping_split_carryover_preserves_priority_pending_scope_review(self):
        monthly, items, plan = self.learning_setup()
        october = self.monthly('oct', '2026-10-01', '2026-10-31')
        self.store.save_monthly_plan(october, True)
        carry = dict(id='shared', monthly_item_id='item-0', period_id='oct', subject='History', learning='unfinished old scope', evidence='teacher note', created_date='2026-10-01', state='outstanding')
        self.store.save_period_review(october, '2026-10-01', [carry], True)
        bundle = self.regroup_bundle(monthly, items)
        bundle['items'].append({**bundle['items'][-1], 'id': 'second-child', 'replacement_from': ['item-0']})
        self.store.apply_reviewed_regrouping(monthly, bundle, True)
        saved = self.store.list_carryover()[0]
        self.assertNotIn('monthly_item_id', saved)
        self.assertEqual(saved['state'], 'outstanding')
        self.assertEqual(saved['learning'], 'unfinished old scope')
        self.assertEqual(set(saved['candidate_monthly_item_ids']), {'replacement', 'second-child'})
        self.assertTrue(saved['link_requires_review'])

    def test_item_backup_roundtrip_and_invalid_reference_atomic(self):
        monthly, items, plan = self.learning_setup()
        self.store.save_lesson_progress(plan['planning_date'], plan['plan_id'], outcomes(plan))
        backup = self.store.export_backup()
        with self.store._connection() as connection:
            for table in ['monthly_item_updates', 'monthly_learning_items', 'period_reviews', 'carryover_items', 'lesson_progress', 'day_plans', *DOCUMENTS, 'actual_progress', 'monthly_plans']:
                connection.execute(f'DELETE FROM {table}')
        bad = json.loads(json.dumps(backup))
        bad['monthly_item_updates'][0]['item_id'] = 'unknown'
        with self.assertRaises(StorageError):
            self.store.restore_backup(bad)
        self.assertTrue(self.store.restore_backup(backup))
        self.assertEqual(self.store.list_learning_items()[0]['status'], 'In progress')
        row = self.store.load_progress_history()[0]
        recorded = row['lessons']
        recorded[1].update(status='Not taught')
        self.store.correct_lesson_progress(row['id'], row['planning_date'], recorded)
        self.assertTrue(all(i['status'] == 'Not started' for i in self.store.list_learning_items()))


    def test_new_explicit_teacher_outcome_can_reopen_completed_item(self):
        from monthly_learning import project
        item = dict(id='item', description='letter')
        updates = [dict(id='a', item_id='item', date='2026-10-01', order=1, status='Completed', remaining='', evidence='teacher whole item finished', manual=True), dict(id='b', item_id='item', date='2026-10-02', order=2, status='In progress', remaining='last paragraph', evidence='teacher accepted correction', accepted=True)]
        self.assertEqual(project([item], updates)[0]['remaining'], 'last paragraph')
        updates[1]['accepted'] = False
        self.assertEqual(project([item], updates)[0]['status'], 'Completed')

    def test_shared_item_lesson_carryover_completion_and_correction(self):
        monthly, items, plan = self.learning_setup()
        october = self.monthly('oct', '2026-10-01', '2026-10-31')
        self.store.save_monthly_plan(october, True)
        carry = dict(id='shared', monthly_item_id='item-0', period_id='oct', subject='History', learning='History aspect 0', evidence='teacher carryover', created_date='2026-10-01', state='outstanding')
        self.store.save_period_review(october, '2026-10-01', [carry], True)
        plan = sample_plan('2026-10-01')
        plan['monthly_plan'] = {k: october[k] for k in ('id', 'title', 'start_date', 'end_date')}
        plan['lessons'][1]['carryover_ids'] = ['shared']
        plan['lessons'][1]['monthly_item_links'] = [dict(item_id='item-0', coverage='complete outstanding activity')]
        self.store.save_day_plan(plan)
        recorded = outcomes(plan)
        self.store.save_lesson_progress('2026-10-01', plan['plan_id'], recorded)
        self.assertEqual(self.store.list_carryover()[0]['state'], 'outstanding')
        recorded[1].update(status='Completed', completed_carryover_ids=['shared'])
        self.store.save_lesson_progress('2026-10-01', plan['plan_id'], recorded)
        self.assertEqual(self.store.list_learning_items()[0]['status'], 'Completed')
        self.assertEqual(self.store.list_carryover()[0]['state'], 'completed')
        recorded[1].update(status='Not taught', completed_carryover_ids=[])
        self.store.correct_lesson_progress(self.store.load_progress_history()[0]['id'], '2026-10-01', recorded)
        self.assertEqual(self.store.list_carryover()[0]['state'], 'outstanding')
        self.assertEqual(self.store.list_learning_items()[0]['status'], 'Not started')

    def test_unverified_extraction_cannot_replace_items(self):
        monthly, items, plan = self.learning_setup()
        before = self.store.export_backup()
        current = self.store.list_learning_items()
        current[0]['source'] = 'invented document quotation'
        with self.assertRaises(StorageError):
            self.store.save_learning_items(monthly, current)
        self.assertEqual(before, self.store.export_backup())

    def test_merge_retains_remaining_evidence_and_historical_ids(self):
        monthly, items, plan = self.learning_setup()
        self.store.correct_learning_item('item-0', 'Completed', '', 'aspect zero finished', True)
        self.store.correct_learning_item('item-1', 'In progress', 'only final letter unfinished', 'teacher evidence', False)
        edited = self.store.list_learning_items()
        for item in edited[:2]:
            item['archived'] = True
        merged = {**items[0], 'id': 'merged', 'description': 'Merged objective', 'merged_from': ['item-0', 'item-1']}
        self.store.save_learning_items(monthly, edited + [merged])
        current = next(i for i in self.store.list_learning_items() if i['id'] == 'merged')
        self.assertEqual(current['remaining'], 'only final letter unfinished')
        self.assertEqual(current['status'], 'In progress')
        self.assertEqual(self.store.load_day('2026-09-30')['plan']['lessons'][1]['monthly_item_links'][0]['item_id'], 'item-0')

if __name__ == "__main__":
    unittest.main()
